import { FaPhoneAlt } from "react-icons/fa";
import { FaHouse } from "react-icons/fa6";
import { LuSiren } from "react-icons/lu";
import { MdOutlineFastfood } from "react-icons/md";

export const RESOURCESCHAT = [
  // ─────────────────────────────────────────────
  // HEALTH
  // ─────────────────────────────────────────────
  {
    id: 1,
    name: "Chester County Hospital",
    category: "health",
    urgency: "immediate",
    description:
      "Full-service hospital providing emergency care, surgery, maternity, and specialty services.",
    hours: "24/7",
    phone: "(610) 431-5000",
    embed: "https://maps.app.goo.gl/XMESHko2gZCahrFc9",
    website:
      "https://www.pennmedicine.org/locations/entity/chester-county-hospital",
    high_need: true,
    addr: "701 E Marshall St, West Chester, PA 19380",
    rating: 2.8,
  },
  {
    id: 2,
    name: "Paoli Hospital",
    category: "health",
    urgency: "immediate",
    description:
      "Acute care hospital offering emergency, cardiac, and surgical services.",
    hours: "24/7",
    phone: "(484) 565-1000",
    embed: "https://maps.app.goo.gl/rf3VhfvkU41ovK618",
    website: "https://www.mainlinehealth.org/locations/paoli-hospital",
    high_need: true,
    addr: "255 W Lancaster Ave, Paoli, PA 19301",
    rating: 3.3,
  },
  {
    id: 3,
    name: "Penn Medicine Southern Chester County",
    category: "health",
    urgency: "immediate",
    description:
      "Emergency department and outpatient services in southern Chester County.",
    hours: "24/7",
    phone: "(610) 869-1000",
    embed: "https://maps.app.goo.gl/Rmw78m4swBHNCNAp9",
    website: "https://www.pennmedicine.org",
    high_need: true,
    addr: "455 Woodview Rd, West Grove, PA 19390",
    rating: 3.6,
  },
  {
    id: 4,
    name: "ChesPenn Health Services",
    category: "health",
    urgency: "general",
    description:
      "Community health center offering primary care, dental, and behavioral health.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(610) 383-3888",
    embed: "https://maps.app.goo.gl/7QMDzmXcy2NfGXfx5",
    website: "https://chespenn.org",
    high_need: false,
    addr: "125 E 9th St, Chester, PA 19013",
    rating: 2.8,
  },
  {
    id: 5,
    name: "Community Volunteers in Medicine",
    category: "health",
    urgency: "general",
    description: "Free medical and dental care for uninsured adults.",
    hours: "Mon–Thu 9am–5pm",
    phone: "(610) 836-5990",
    embed: "https://maps.app.goo.gl/sdNaygGjSErTHDnbA",
    website: "https://cvim.org",
    high_need: false,
    addr: "300 B Lawrence Dr, West Chester, PA 19380",
    rating: 4.8,
  },
  {
    id: 6,
    name: "La Comunidad Hispana Health Center",
    category: "health",
    urgency: "general",
    description:
      "Bilingual primary care, women's health, and pediatric services.",
    hours: "Mon–Fri 8am–6pm",
    phone: "(610) 444-7550",
    embed: "https://maps.app.goo.gl/EbELqudzpKH7yYGBA",
    website: "https://lchcommunityhealth.org",
    high_need: false,
    addr: "731 W Cypress St, Kennett Square, PA 19348",
    rating: 3.8,
  },
  {
    id: 7,
    name: "Phoenixville Hospital",
    category: "health",
    urgency: "immediate",
    description: "Emergency care, surgery, and inpatient services.",
    hours: "24/7",
    phone: "(610) 983-1000",
    embed: "https://maps.app.goo.gl/QStB8wS2NPTgaev78",
    website: "https://towerhealth.org",
    high_need: true,
    addr: "140 Nutt Rd, Phoenixville, PA 19460",
    rating: 3.5,
  },
  {
    id: 8,
    name: "Devereux Advanced Behavioral Health",
    category: "health",
    urgency: "general",
    description: "Mental health, autism, and behavioral health services.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(610) 431-8900",
    embed: "https://maps.app.goo.gl/jaN7F5qD2YH2VjMy8",
    website: "https://www.devereux.org",
    high_need: false,
    addr: "655 Sugartown Rd, Malvern, PA 19355",
    rating: 2.3,
  },
  {
    id: 9,
    name: "Penn Medicine Exton",
    category: "health",
    urgency: "general",
    description:
      "Outpatient center with primary care, imaging, and specialty services.",
    hours: "Mon–Fri 7am–7pm",
    phone: "(484) 565-8600",
    embed: "https://maps.app.goo.gl/YVLw67bDPBszWHfC6",
    website: "https://www.pennmedicine.org",
    high_need: false,
    addr: "700 W Lincoln Hwy, Exton, PA 19341",
    rating: 3.3,
  },
  {
    id: 10,
    name: "Chester County Health Department",
    category: "health",
    urgency: "general",
    description:
      "Public health services including immunizations and health screenings.",
    hours: "Mon–Fri 8:30am–4:30pm",
    phone: "(610) 344-6225",
    embed: "https://maps.app.goo.gl/WCHbvajgsAsD4ZM4A",
    website: "https://www.chesco.org/healthdept",
    high_need: false,
    addr: "601 Westtown Rd, West Chester, PA 19382",
    rating: 2.9,
  },
  {
    id: 11,
    name: "Main Line Health Center Exton",
    category: "health",
    urgency: "general",
    description: "Primary care, specialty care, and outpatient services.",
    hours: "Mon–Fri 8am–6pm",
    phone: "(484) 565-1293",
    embed: "https://maps.app.goo.gl/q11w3UeSkSjuArwNA",
    website: "https://www.mainlinehealth.org",
    high_need: false,
    addr: "154 Exton Square Pkwy, Exton, PA 19341",
    rating: 4.1,
  },
  {
    id: 12,
    name: "Patient First Downingtown",
    category: "health",
    urgency: "immediate",
    description: "Urgent care, primary care, and lab services.",
    hours: "Daily 8am–10pm",
    phone: "(610) 873-6400",
    embed: "https://maps.app.goo.gl/han4AoDuVmGLnSkR6",
    website: "https://www.patientfirst.com",
    high_need: true,
    addr: "967 E Lancaster Ave, Downingtown, PA 19335",
    rating: 4.2,
  },
  {
    id: 13,
    name: "AFC Urgent Care West Chester",
    category: "health",
    urgency: "immediate",
    description: "Walk-in urgent care with extended hours.",
    hours: "Daily 8am–8pm",
    phone: "(484) 999-0211",
    embed: "https://maps.app.goo.gl/FtxY2neaJkcTuwTT9",
    website: "https://www.afcurgentcare.com",
    high_need: true,
    addr: "510 E Gay St, West Chester, PA 19380",
    rating: 4.6,
  },
  {
    id: 14,
    name: "Holcomb Behavioral Health Systems",
    category: "health",
    urgency: "general",
    description: "Mental health and substance use treatment services.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 363-1488",
    embed: "https://maps.app.goo.gl/iaYiqNhaEDHD5tER8",
    website: "https://www.chimes.org",
    high_need: false,
    addr: "467 Creamery Way, Exton, PA 19341",
    rating: 2.8,
  },
  {
    id: 15,
    name: "Gaudenzia Coatesville",
    category: "health",
    urgency: "immediate",
    description: "Addiction treatment and recovery services.",
    hours: "24/7",
    phone: "(610) 383-9600",
    embed: "https://maps.app.goo.gl/Bq7indT79RUe59jQA",
    website: "https://www.gaudenzia.org",
    high_need: true,
    addr: "31 S 10th Ave, Coatesville, PA 19320",
    rating: 1.7,
  },
  {
    id: 16,
    name: "Chester County Eye Care",
    category: "health",
    urgency: "general",
    description: "Vision care, exams, and treatment services.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 696-1230",
    embed: "https://maps.app.goo.gl/gAbew5XKzVLHaDBm9",
    website: "https://www.chestercountyeyecare.com/",
    high_need: false,
    addr: "915 Old Fern Hill Rd, West Chester, PA 19380",
    rating: 4.8,
  },
  {
    id: 17,
    name: "Penn Care at Home",
    category: "health",
    urgency: "general",
    description: "Home health and hospice care services.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(800) 789-7366",
    embed: "https://maps.app.goo.gl/3eBonDAboQv2mQUR7",
    website: "https://www.pennmedicine.org",
    high_need: false,
    addr: "150 Monument Rd, Ste 300, Bala Cynwyd, PA 19004",
    rating: 2.6,
  },
  {
    id: 18,
    name: "Chester County Dental Arts",
    category: "health",
    urgency: "general",
    description: "Comprehensive dental care services.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 431-4444",
    embed: "https://maps.app.goo.gl/EUBwybyTDD4y2AUo7",
    website: "https://www.chestercountydentalarts.com/",
    high_need: false,
    addr: "3105 C G Zinn Rd, Thorndale, PA 19372",
    rating: 4.7,
  },
  {
    id: 19,
    name: "Penn Medicine West Chester Pike Health Center",
    category: "health",
    urgency: "general",
    description: "Primary and specialty outpatient care services.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(610) 696-2850",
    embed: "https://maps.app.goo.gl/RNT89geqcRyG7LRf9",
    website: "https://www.pennmedicine.org",
    high_need: false,
    addr: "301 West Chester Pike, Ste 201, Havertown, PA 19083",
    rating: 3.0,
  },
  {
    id: 20,
    name: "Nemours Children's Health Exton",
    category: "health",
    urgency: "general",
    description: "Pediatric primary and specialty care.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(610) 594-9000",
    embed: "https://maps.app.goo.gl/fw3YdajPGy62GDo38",
    website: "https://www.nemours.org",
    high_need: false,
    addr: "101 Arrandale Blvd, Ste 103, Exton, PA 19341",
    rating: 4.4,
  },
  {
    id: 21,
    name: "Chester County OB/GYN Associates",
    category: "health",
    urgency: "general",
    description: "Women's health, prenatal, and gynecological services.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(610) 692-3434",
    embed: "https://maps.app.goo.gl/hbbLxhKVTkvsmrNA7",
    website:
      "https://axiawh.com/locations/chester-county-ob-gyn-of-west-chester/",
    high_need: false,
    addr: "915 Old Fern Hill Rd, West Chester, PA 19380",
    rating: 3.4,
  },
  {
    id: 22,
    name: "Pennsylvania Psychiatric Institute",
    category: "health",
    urgency: "general",
    description: "Mental health evaluations and psychiatric care referrals.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(717) 782-3131",
    embed: "https://maps.app.goo.gl/V2KG6SPS8AT5PEB87",
    website: "https://ppimhs.org/",
    high_need: false,
    addr: "2501 N 3rd St, Harrisburg, PA 17110",
    rating: 2.6,
  },
  {
    id: 23,
    name: "Better Beginnings Maternal Care",
    category: "health",
    urgency: "general",
    description: "Maternal health, prenatal education, and support services.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 344-5370",
    embed: "https://maps.app.goo.gl/kpT7CcVggWF4hqUA9",
    website: "https://ccmchc.org",
    high_need: false,
    addr: "1475 Phoenixville Pike, Ste 12, West Chester, PA 19380",
    rating: 3.8,
  },
  {
    id: 24,
    name: "Main Line Health Behavioral Services",
    category: "health",
    urgency: "general",
    description: "Outpatient therapy, psychiatry, and addiction treatment.",
    hours: "Mon–Fri 8am–6pm",
    phone: "(484) 565-1130",
    embed: "https://maps.app.goo.gl/iVKzGc95rteLDDEP6",
    website: "https://www.mainlinehealth.org",
    high_need: false,
    addr: "101 S Bryn Mawr Ave, Ste 340, Bryn Mawr, PA 19010",
    rating: 4.0,
  },
  {
    id: 25,
    name: "Tower Health Medical Group Family Medicine",
    category: "health",
    urgency: "general",
    description: "Primary care and chronic disease management.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(610) 383-8300",
    embed: "https://maps.app.goo.gl/sio15u9Kyjn95wGo7",
    website: "https://towerhealth.org",
    high_need: false,
    addr: "1 Medical Center Blvd, Upland, PA 19013",
    rating: 5.0,
  },
  {
    id: 26,
    name: "Penn Medicine Dermatology West Chester",
    category: "health",
    urgency: "general",
    description: "Skin care, dermatology, and treatment services.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(610) 436-4444",
    embed: "https://maps.app.goo.gl/M95KhiSTGMk9LfPB8",
    website: "https://mainlinederm.com",
    high_need: false,
    addr: "1246 Wrights Ln, West Chester, PA 19380",
    rating: 4.8,
  },
  {
    id: 27,
    name: "Abramson Cancer Center",
    category: "health",
    urgency: "immediate",
    description: "Oncology services including chemotherapy and support care.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(610) 738-2500",
    embed: "https://maps.app.goo.gl/buwz4AiLZtzjDvtB8",
    website:
      "https://www.pennmedicine.org/practices/abramson-cancer-center-west-chester",
    high_need: true,
    addr: "440 E Marshall St, Ste 101, West Chester, PA 19380",
    rating: 4.2,
  },
  {
    id: 28,
    name: "Penn Medicine Cardiology",
    category: "health",
    urgency: "general",
    description: "Heart care, diagnostics, and cardiology services.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(484) 565-8600",
    embed: "https://maps.app.goo.gl/mHxomKpAWXun2UjSA",
    website:
      "https://www.pennmedicine.org/practices/chester-county-cardiology-associates-west-grove",
    high_need: false,
    addr: "600 E Marshall St, Ste 303, West Chester, PA 19380",
    rating: 4.0,
  },
  {
    id: 29,
    name: "Penn Neurology",
    category: "health",
    urgency: "general",
    description: "Neurological evaluations and treatment services.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 696-1234",
    embed: "https://maps.app.goo.gl/54eWfbW6sxaxX4Y2A",
    website: "https://www.pennmedicine.org/practices/neurology-westtown",
    high_need: false,
    addr: "200 Willowbrook Ln, Ste 210, West Chester, PA 19382",
    rating: 4.0,
  },
  {
    id: 30,
    name: "Penn Medicine Orthopedics",
    category: "health",
    urgency: "general",
    description: "Bone, joint, and sports injury treatment.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(610) 444-0500",
    embed: "https://maps.app.goo.gl/PeLEExfoA2TkmHmQ7",
    website: "https://www.pennmedicine.org/specialties/orthopaedics",
    high_need: false,
    addr: "479 Thomas Jones Way, Ste 300, Exton, PA 19341",
    rating: 3.7,
  },
  {
    id: 31,
    name: "Kinetic Chester Springs",
    category: "health",
    urgency: "general",
    description: "Rehabilitation and physical therapy services.",
    hours: "Mon–Fri 7am–8pm",
    phone: "(610) 430-9000",
    embed: "https://maps.app.goo.gl/kN6Th7xw5Htk9DFD8",
    website: "https://kineticptpa.com/locations/chester-springs/",
    high_need: false,
    addr: "163 Pottstown Pike, Chester Springs, PA 19425",
    rating: 5.0,
  },
  {
    id: 32,
    name: "Brandywine Valley Counseling Services",
    category: "health",
    urgency: "general",
    description: "Mental health counseling and therapy.",
    hours: "Mon–Fri 9am–6pm",
    phone: "(610) 383-9600",
    embed: "https://maps.app.goo.gl/iot6PQ2KuQPUQfxk7",
    website: "http://brandywinevalleycc.com/",
    high_need: false,
    addr: "999 West Chester Pike, B-1, West Chester, PA 19382",
    rating: 4.0,
  },
  {
    id: 33,
    name: "Penn Medicine Gastroenterology",
    category: "health",
    urgency: "general",
    description: "Digestive health and GI treatment services.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(610) 738-2400",
    embed: "https://maps.app.goo.gl/J7hr4chWBUAcjf5r7",
    website:
      "https://usdigestivehealth.com/for-patients/locations/west-chester/",
    high_need: false,
    addr: "915 Old Fern Hill Rd, Ste 300, West Chester, PA 19380",
    rating: 4.6,
  },
  {
    id: 34,
    name: "Foot and Ankle Center of Chester County",
    category: "health",
    urgency: "general",
    description: "Foot and ankle care services.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 692-1118",
    embed: "https://maps.app.goo.gl/JcZ3uQJF236Q8VKt9",
    website: "http://footandankleofchestercounty.com/",
    high_need: false,
    addr: "520 Maple Ave, Ste 3, West Chester, PA 19380",
    rating: 4.6,
  },
  {
    id: 35,
    name: "Penn Sleep Center Westtown",
    category: "health",
    urgency: "general",
    description: "Sleep studies and treatment for sleep disorders.",
    hours: "By appointment",
    phone: "(610) 738-2300",
    embed: "https://maps.app.goo.gl/1bWiCrxnEETR2NjJA",
    website:
      "https://www.pennmedicine.org/practices/penn-sleep-center-westtown",
    high_need: false,
    addr: "200 Willowbrook Ln, Ste 210, West Chester, PA 19382",
    rating: 3.8,
  },
  {
    id: 36,
    name: "Penn Medicine Pain Management",
    category: "health",
    urgency: "general",
    description: "Chronic pain evaluation and treatment services.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(610) 738-2600",
    embed: "https://maps.app.goo.gl/vSzsngNb2R8NL8yF8",
    website: "https://www.pennmedicine.org/practices/pain-medicine-westtown",
    high_need: false,
    addr: "210 Willowbrook Ln, West Chester, PA 19382",
    rating: 3.0,
  },

  // ─────────────────────────────────────────────
  // FOOD
  // ─────────────────────────────────────────────
  {
    id: 37,
    name: "Chester County Food Bank",
    category: "food",
    urgency: "immediate",
    description:
      "Countywide food distribution, mobile pantries, and meal programs.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 873-6000",
    embed: "https://maps.app.goo.gl/DDMwXzMBkKWg718w5",
    website: "https://chestercountyfoodbank.org",
    high_need: true,
    addr: "650 Pennsylvania Dr, Exton, PA 19341",
    rating: 4.6,
  },
  {
    id: 38,
    name: "West Chester Food Cupboard",
    category: "food",
    urgency: "general",
    description:
      "Supplemental groceries for residents, no appointment required on select days.",
    hours: "Tue & Fri 10am–1pm",
    phone: "(610) 696-6877",
    embed: "https://maps.app.goo.gl/ZikzwJbLhQV2oC4A6",
    website: "https://westchesterfoodcupboard.org",
    high_need: false,
    addr: "431 S Bolmar St, West Chester, PA 19382",
    rating: 4.9,
  },
  {
    id: 39,
    name: "Phoenixville Area Community Services (PACS)",
    category: "food",
    urgency: "general",
    description: "Food pantry and emergency assistance for local residents.",
    hours: "Mon–Fri 9am–3pm",
    phone: "(610) 933-1105",
    embed: "https://maps.app.goo.gl/eBjRjZzEW6ovy5rn9",
    website: "https://pacsphx.org",
    high_need: false,
    addr: "101 Buchanan St, Phoenixville, PA 19460",
    rating: 4.9,
  },
  {
    id: 40,
    name: "Kennett Area Community Service",
    category: "food",
    urgency: "general",
    description: "Food pantry and emergency financial assistance.",
    hours: "Mon–Fri 9am–4pm",
    phone: "(610) 925-3556",
    embed: "https://maps.app.goo.gl/bG3YoMD5LBPJLRiQ8",
    website: "https://kacsimpact.org/",
    high_need: false,
    addr: "136 W Cedar St, Kennett Square, PA 19348",
    rating: 4.5,
  },
  {
    id: 41,
    name: "Oxford Neighborhood Services Center",
    category: "food",
    urgency: "general",
    description: "Food pantry and support services for families.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 932-8557",
    embed: "https://maps.app.goo.gl/XBxwC3Kp9sgZeHF3A",
    website: "https://www.oxfordnsc.org/",
    high_need: false,
    addr: "35 N 3rd St, Oxford, PA 19363",
    rating: 4.4,
  },
  {
    id: 42,
    name: "Coatesville Salvation Army Food Pantry",
    category: "food",
    urgency: "immediate",
    description: "Emergency food assistance and hot meals.",
    hours: "Mon–Fri 9am–4pm",
    phone: "(610) 384-2954",
    embed: "https://maps.app.goo.gl/3mwhcktELuhD4jPj7",
    website:
      "https://easternusa.salvationarmy.org/eastern-pennsylvania/coatesville-pa/",
    high_need: true,
    addr: "669 Lincoln Hwy E, Coatesville, PA 19320",
    rating: 4.1,
  },
  {
    id: 43,
    name: "Lord's Pantry of Downingtown",
    category: "food",
    urgency: "general",
    description: "Weekly food distribution for individuals and families.",
    hours: "Sat mornings",
    phone: "(610) 873-1149",
    embed: "https://maps.app.goo.gl/z43THKprAQDCzyPD6",
    website: "http://www.lordspantryofdowningtown.org/",
    high_need: false,
    addr: "101 E Lancaster Ave, Downingtown, PA 19335",
    rating: 4.9,
  },
  {
    id: 44,
    name: "Good Samaritan Services Phoenixville",
    category: "food",
    urgency: "immediate",
    description: "Daily hot meals and food pantry access.",
    hours: "Daily 11:30am–1pm",
    phone: "(610) 933-0741",
    embed: "https://maps.app.goo.gl/qdfviFUHaH3AuT246",
    website: "https://goodsamservices.org",
    high_need: true,
    addr: "104 High St, Phoenixville, PA 19460",
    rating: 3.7,
  },
  {
    id: 45,
    name: "St. Agnes Day Room",
    category: "food",
    urgency: "immediate",
    description: "Free meals and support services for those in need.",
    hours: "Mon–Fri 9am–2pm",
    phone: "(610) 696-8746",
    embed: "https://maps.app.goo.gl/D9ZUTLRcMSAyqEN16",
    website: "https://saintagnesparish.org/st-agnes-day-room-1",
    high_need: true,
    addr: "233 W Gay St, West Chester, PA 19380",
    rating: 5.0,
  },
  {
    id: 46,
    name: "Meals on Wheels Chester County",
    category: "food",
    urgency: "general",
    description: "Home-delivered meals for seniors and disabled residents.",
    hours: "Mon–Fri",
    phone: "(610) 430-8500",
    embed: "https://maps.app.goo.gl/fV1wknw1kb3H1w2p6",
    website: "http://www.mowcc.org/",
    high_need: false,
    addr: "404 Willowbrook Ln, West Chester, PA 19382",
    rating: 4.5,
  },
  {
    id: 47,
    name: "Calvary Fellowship Food Pantry",
    category: "food",
    urgency: "general",
    description: "Food assistance and grocery distribution.",
    hours: "Weekly",
    phone: "(610) 384-8744",
    embed: "https://maps.app.goo.gl/duWgetQX1xD96Cp56",
    website: "https://calvaryfellowship.com",
    high_need: false,
    addr: "500 Brandywine Dr, Chadds Ford, PA 19317",
    rating: 4.9,
  },
  {
    id: 48,
    name: "St. Rocco Church",
    category: "food",
    urgency: "general",
    description: "Community food support for families in need.",
    hours: "Weekly",
    phone: "(610) 384-2481",
    embed: "https://maps.app.goo.gl/NbKLSkPY7BZkc7DA9",
    website: "https://www.stroccochurch.org/",
    high_need: false,
    addr: "104 E Avon Ave, Avondale, PA 19311",
    rating: 4.8,
  },
  {
    id: 49,
    name: "West Grove United Methodist Church",
    category: "food",
    urgency: "general",
    description: "Food assistance for local residents.",
    hours: "Weekly",
    phone: "(610) 869-9334",
    embed: "https://maps.app.goo.gl/BNcxFZehWvnML4A2A",
    website: "http://westgroveumc.org/",
    high_need: false,
    addr: "300 N Guernsey Rd, West Grove, PA 19390",
    rating: 4.9,
  },
  {
    id: 50,
    name: "Octorara Area Food Cupboard",
    category: "food",
    urgency: "general",
    description: "Food and essentials distribution.",
    hours: "Tue & Wed 12:45pm–3:45pm",
    phone: "(610) 857-3399",
    embed: "https://maps.app.goo.gl/CWKpLYhUiJKd3dFBA",
    website: "http://octfood.com/",
    high_need: false,
    addr: "714 Main St, Parkesburg, PA 19365",
    rating: 4.8,
  },
  {
    id: 51,
    name: "Honey Brook Food Pantry",
    category: "food",
    urgency: "general",
    description: "Local food assistance for residents.",
    hours: "Weekly",
    phone: "(610) 273-2848",
    embed: "https://maps.app.goo.gl/ULqRQjwpfoHdSC7M6",
    website: "https://www.honeybrookfoodpantry.org/",
    high_need: false,
    addr: "5064 Horseshoe Pike, Honey Brook, PA 19344",
    rating: 4.9,
  },

  // ─────────────────────────────────────────────
  // HOUSING
  // ─────────────────────────────────────────────
  {
    id: 52,
    name: "Chester County Housing Authority",
    category: "housing",
    urgency: "general",
    description:
      "Section 8 vouchers, public housing, and rental assistance programs.",
    hours: "Mon–Fri 8:30am–4:30pm",
    phone: "(610) 436-9200",
    embed: "https://maps.app.goo.gl/ckdDujqQSip3zTtw9",
    website: "https://www.haccnet.org",
    high_need: false,
    addr: "30 W Barnard St, West Chester, PA 19382",
    rating: 2.4,
  },
  {
    id: 53,
    name: "Good Samaritan Services",
    category: "housing",
    urgency: "immediate",
    description:
      "Emergency shelter, transitional housing, and homelessness prevention.",
    hours: "24/7",
    phone: "(610) 933-0741",
    embed: "https://maps.app.goo.gl/C3yTpAoGqwYvSw2C7",
    website: "https://goodsamservices.org",
    high_need: true,
    addr: "104 High St, Phoenixville, PA 19460",
    rating: 3.7,
  },
  {
    id: 54,
    name: "Bridge of Hope Chester County",
    category: "housing",
    urgency: "general",
    description:
      "Transitional housing and support for single mothers facing homelessness.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 280-0280",
    embed: "https://maps.app.goo.gl/8Jv1FbfkXogSnnWj6",
    website: "https://bridgeofhopeinc.org",
    high_need: false,
    addr: "1 N Bacton Hill Rd, Malvern, PA 19355",
    rating: 5.0,
  },
  {
    id: 55,
    name: "Safe Harbor of Chester County",
    category: "housing",
    urgency: "immediate",
    description:
      "Emergency shelter and supportive services for people experiencing homelessness.",
    hours: "24/7",
    phone: "(610) 692-6550",
    embed: "https://maps.app.goo.gl/iF6eiAKB6qhofjzK6",
    website: "https://safeharborofcc.org",
    high_need: true,
    addr: "20 N Matlack St, West Chester, PA 19380",
    rating: 4.3,
  },
  {
    id: 56,
    name: "Domestic Violence Center of Chester County",
    category: "housing",
    urgency: "immediate",
    description:
      "Emergency shelter and housing support for survivors of domestic violence.",
    hours: "24/7 hotline",
    phone: "(610) 431-1430",
    embed: "https://maps.app.goo.gl/BbgEF5dZU3normYo6",
    website: "https://dvccc.com",
    high_need: true,
    addr: "1001 Lincoln Hwy E, Ste 103, Coatesville, PA 19320",
    rating: 3.0,
  },
  {
    id: 57,
    name: "Phoenixville Housing Authority",
    category: "housing",
    urgency: "general",
    description: "Public housing and housing choice voucher programs.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 933-5338",
    embed: "https://maps.app.goo.gl/bJiEkG4RwX5uuL4v9",
    website: "http://www.haccnet.org/",
    high_need: false,
    addr: "300 High St, Phoenixville, PA 19460",
    rating: 5.0,
  },
  {
    id: 58,
    name: "Friends Association for Care & Protection",
    category: "housing",
    urgency: "immediate",
    description:
      "Emergency family shelter and homelessness prevention services.",
    hours: "24/7",
    phone: "(610) 431-3598",
    embed: "https://maps.app.goo.gl/GHTPeX4cLP5AC9Na9",
    website: "https://friendsassoc.org",
    high_need: true,
    addr: "825 Paoli Pike, West Chester, PA 19380",
    rating: 4.5,
  },
  {
    id: 59,
    name: "Housing Partnership of Chester County",
    category: "housing",
    urgency: "general",
    description:
      "Housing counseling, foreclosure prevention, and financial education.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 518-1522",
    embed: "https://maps.app.goo.gl/YGCqnQWhDVqXBMyk9",
    website: "https://housingpartnershipcc.org",
    high_need: false,
    addr: "41 W Lancaster Ave, Downingtown, PA 19335",
    rating: 5.0,
  },
  {
    id: 60,
    name: "Open Hearth Inc.",
    category: "housing",
    urgency: "general",
    description: "Transitional and permanent housing for single men.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 430-3816",
    embed: "https://maps.app.goo.gl/GmJveTtkweySTtyE7",
    website: "https://theopenhearth.org",
    high_need: false,
    addr: "701 S Main St, Phoenixville, PA 19460",
    rating: 4.4,
  },
  {
    id: 61,
    name: "Oxford Area Neighborhood Services Center",
    category: "housing",
    urgency: "general",
    description: "Rental assistance and housing support services.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 932-8557",
    embed: "https://maps.app.goo.gl/mDAQB5PhbuPDcEc2A",
    website: "https://www.oxfordnsc.org/",
    high_need: false,
    addr: "35 N 3rd St, Oxford, PA 19363",
    rating: 4.4,
  },
  {
    id: 62,
    name: "Kennett Area Community Service Housing Assistance",
    category: "housing",
    urgency: "general",
    description: "Emergency housing assistance and rent support.",
    hours: "Mon–Fri 9am–4pm",
    phone: "(610) 925-3556",
    embed: "https://maps.app.goo.gl/27VeXj4yMPNaeTkT6",
    website: "https://kacsimpact.org",
    high_need: false,
    addr: "136 W Cedar St, Kennett Square, PA 19348",
    rating: 4.5,
  },
  {
    id: 63,
    name: "Salvation Army Coatesville Housing Assistance",
    category: "housing",
    urgency: "immediate",
    description: "Emergency shelter referrals and rental assistance.",
    hours: "Mon–Fri 9am–4pm",
    phone: "(610) 384-2954",
    embed: "https://maps.app.goo.gl/p95GPiAmWmbjBLV59",
    website:
      "https://easternusa.salvationarmy.org/eastern-pennsylvania/coatesville-pa/",
    high_need: true,
    addr: "669 Lincoln Hwy E, Coatesville, PA 19320",
    rating: 3.0,
  },
  {
    id: 64,
    name: "St. Agnes Day Room Housing Support",
    category: "housing",
    urgency: "immediate",
    description:
      "Day shelter with connections to housing resources and case management.",
    hours: "Mon–Fri 9am–2pm",
    phone: "(610) 696-8746",
    embed: "https://maps.app.goo.gl/P1iYMKom7QtvNTvn7",
    website: "https://saintagnesparish.org/st-agnes-day-room-1",
    high_need: true,
    addr: "233 W Gay St, West Chester, PA 19380",
    rating: 5.0,
  },
  {
    id: 65,
    name: "Community Action Agency of Delaware County (Chester County Support)",
    category: "housing",
    urgency: "general",
    description:
      "Rental and utility assistance programs for low-income residents.",
    hours: "Mon–Fri 8:30am–4:30pm",
    phone: "(610) 521-8770",
    embed: "https://maps.app.goo.gl/iMvmyDApJfk3bFnK9",
    website: "https://caadc.org/",
    high_need: false,
    addr: "1414 Meetinghouse Rd, Boothwyn, PA 19061",
    rating: 3.5,
  },
  {
    id: 66,
    name: "Habitat for Humanity Chester County",
    category: "housing",
    urgency: "general",
    description: "Affordable homeownership opportunities and housing repairs.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 384-7993",
    embed: "https://maps.app.goo.gl/gC1dVEwg2dBfkyRRA",
    website: "https://hfhcc.org",
    high_need: false,
    addr: "1220 Valley Forge Rd, Ste 16, Phoenixville, PA 19460",
    rating: 4.6,
  },
  {
    id: 67,
    name: "PA 211 Southeast Housing Assistance",
    category: "housing",
    urgency: "immediate",
    description:
      "24/7 referral service for emergency housing and shelter resources.",
    hours: "24/7",
    phone: "211",
    embed: "https://maps.app.goo.gl/Evk9qEA28oEuj1BD7",
    website: "http://211sepa.org/",
    high_need: true,
    addr: "Chester County, PA",
    rating: 3.8,
  },
  {
    id: 68,
    name: "Your Way Home",
    category: "housing",
    urgency: "immediate",
    description:
      "Coordinated entry system for people experiencing homelessness in Montgomery County.",
    hours: "Mon–Fri 8:30am–4:30pm",
    phone: "(610) 344-6640",
    embed: "https://maps.app.goo.gl/hQB1DsdTyiLKNZv19",
    website: "http://yourwayhome.org/",
    high_need: true,
    addr: "Human Services Center, Norristown, PA 19404",
    rating: 3.0,
  },
  {
    id: 69,
    name: "Brandywine Valley Active Aging Housing Support",
    category: "housing",
    urgency: "general",
    description:
      "Senior housing referrals and assistance with independent living options.",
    hours: "Mon–Fri 8:30am–4:30pm",
    phone: "(610) 388-7800",
    embed: "https://maps.app.goo.gl/dnew6FW5pGfQrYwj9",
    website: "https://www.bvactiveaging.org/",
    high_need: false,
    addr: "400 Ave of Honor, Coatesville, PA 19320",
    rating: 3.0,
  },
  {
    id: 70,
    name: "PA Housing Finance Agency (PHFA)",
    category: "housing",
    urgency: "general",
    description:
      "Statewide rental assistance, foreclosure prevention, and homebuyer programs.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(855) 827-3466",
    embed: "https://maps.app.goo.gl/Vrumsm7FXe6viiyW8",
    website: "https://www.phfa.org",
    high_need: false,
    addr: "211 N Front St, Harrisburg, PA 17101",
    rating: 2.0,
  },
  {
    id: 71,
    name: "Home of the Sparrow",
    category: "housing",
    urgency: "immediate",
    description:
      "Supportive housing and services for women facing homelessness.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 647-4940",
    embed: "https://maps.app.goo.gl/JPfh8E2bXFnw1EzK7",
    website: "https://homeofthesparrow.org",
    high_need: true,
    addr: "969 Swedesford Rd, Exton, PA 19341",
    rating: 4.4,
  },
  {
    id: 72,
    name: "Human Services Inc. Housing Programs",
    category: "housing",
    urgency: "general",
    description:
      "Affordable housing and behavioral health residential services.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 380-4660",
    embed: "https://maps.app.goo.gl/S365ir5sWXjdEWDWA",
    website: "http://www.humanservicesinc.com/",
    high_need: false,
    addr: "50 James Buchanan Dr, Thorndale, PA 19372",
    rating: 3.4,
  },
  {
    id: 73,
    name: "LCH Community Health Housing Referrals",
    category: "housing",
    urgency: "general",
    description:
      "Connections to housing and social services for underserved populations.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(610) 444-7550",
    embed: "https://maps.app.goo.gl/2RtGSvTqoACUUsLA7",
    website: "https://lchcommunityhealth.org",
    high_need: false,
    addr: "731 W Cypress St, Kennett Square, PA 19348",
    rating: 3.8,
  },
  {
    id: 74,
    name: "Maternal & Child Health Consortium Housing Support",
    category: "housing",
    urgency: "general",
    description: "Housing assistance for families with young children.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 344-5370",
    embed: "https://maps.app.goo.gl/Dyq216u7zPu2MQnHA",
    website: "https://ccmchc.org",
    high_need: false,
    addr: "1475 Phoenixville Pike, Ste 12, West Chester, PA 19380",
    rating: 5.0,
  },
  {
    id: 75,
    name: "PA Department of Human Services Housing Programs",
    category: "housing",
    urgency: "general",
    description: "State assistance for housing, rent, and utilities.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(800) 692-7462",
    embed: "https://maps.app.goo.gl/uG4GrCgqwedSynZG6",
    website: "https://www.dhs.pa.gov",
    high_need: false,
    addr: "801 Market St, Philadelphia, PA 19107",
    rating: 3.6,
  },
  {
    id: 76,
    name: "Catholic Social Services Chester County",
    category: "housing",
    urgency: "general",
    description: "Affordable housing and case management services.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 435-1541",
    embed: "https://maps.app.goo.gl/T6sDYtgnG9LXrss76",
    website: "https://cssphiladelphia.org",
    high_need: false,
    addr: "222 N 17th St, Philadelphia, PA 19103",
    rating: 4.4,
  },
  {
    id: 77,
    name: "United Way of Chester County Housing Help",
    category: "housing",
    urgency: "general",
    description: "Referrals and financial assistance for housing stability.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 429-9400",
    embed: "https://maps.app.goo.gl/EbiciMp4NyLcGUhf8",
    website: "https://unitedwaychestercounty.org",
    high_need: false,
    addr: "150 John Robert Thomas Dr, Exton, PA 19341",
    rating: 5.0,
  },
  {
    id: 78,
    name: "Fair Housing Rights Center in Southeastern Pennsylvania",
    category: "housing",
    urgency: "general",
    description:
      "Fair housing support and legal assistance for discrimination cases.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(267) 419-8918",
    embed: "https://maps.app.goo.gl/g9VRyUffR8XfWsC57",
    website: "http://fairhousingrights.org/",
    high_need: false,
    addr: "444 N 3rd St, Ste 110, Philadelphia, PA 19123",
    rating: 3.6,
  },
  {
    id: 79,
    name: "PA Legal Aid Housing Assistance",
    category: "housing",
    urgency: "immediate",
    description:
      "Free legal help for eviction, foreclosure, and tenant rights.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(877) 429-5994",
    embed: "https://maps.app.goo.gl/8wQW3L2eH9giiDdn8",
    website: "https://www.lasp.org/",
    high_need: true,
    addr: "419 Avenue of the States, Ste 605, Chester, PA 19013",
    rating: 3.4,
  },
  {
    id: 80,
    name: "West Chester Area Senior Center Housing Aid",
    category: "housing",
    urgency: "general",
    description: "Housing assistance and referrals for seniors.",
    hours: "Mon–Fri 8am–4pm",
    phone: "(610) 431-4242",
    embed: "https://maps.app.goo.gl/SZJaz82oUhQdHT1W6",
    website: "https://wcseniors.org/",
    high_need: false,
    addr: "530 E Union St, West Chester, PA 19382",
    rating: 3.0,
  },

  // ─────────────────────────────────────────────
  // JOBS
  // ─────────────────────────────────────────────
  {
    id: 81,
    name: "PA CareerLink Chester County",
    category: "jobs",
    urgency: "general",
    description: "Job search help, resume support, and training programs.",
    hours: "Mon–Fri 8:30am–4:30pm",
    phone: "(610) 280-1010",
    embed: "https://maps.app.goo.gl/QeXC8LNtArSjLPcYA",
    website: "https://www.pacareerlinkchesco.org",
    high_need: false,
    addr: "479 Thomas Jones Way, Ste 500, Exton, PA 19341",
    rating: 3.5,
  },
  {
    id: 82,
    name: "Chester County OIC",
    category: "jobs",
    urgency: "general",
    description: "Workforce training, GED prep, and job placement services.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 692-2344",
    embed: "https://maps.app.goo.gl/jj6Dj2Mjy8PT41T89",
    website: "https://ccoic.org",
    high_need: false,
    addr: "22 N 5th Ave, Coatesville, PA 19320",
    rating: 4.2,
  },
  {
    id: 83,
    name: "Goodwill Keystone Area Job Training",
    category: "jobs",
    urgency: "general",
    description: "Job training and employment placement support.",
    hours: "Mon–Sat 9am–9pm, Sun 10am–7pm",
    phone: "(610) 363-0799",
    embed: "https://maps.app.goo.gl/F3UQSSQJubfep2y5A",
    website: "https://www.yourgoodwill.org",
    high_need: false,
    addr: "39 Marchwood Rd, Exton, PA 19341",
    rating: 3.8,
  },
  {
    id: 84,
    name: "Technical College High School Adult Education",
    category: "jobs",
    urgency: "general",
    description: "Adult vocational training and certification programs.",
    hours: "Varies by program",
    phone: "(610) 692-1964",
    embed: "https://maps.app.goo.gl/9RhfH1Ta6A9XTtPP8",
    website: "https://www.cciu.org/tchs",
    high_need: false,
    addr: "1580 Charter Rd, West Grove, PA 19390",
    rating: 4.3,
  },
  {
    id: 85,
    name: "Delaware County Community College (Exton Center)",
    category: "jobs",
    urgency: "general",
    description: "Career training, certifications, and workforce programs.",
    hours: "Mon–Fri 8am–6pm",
    phone: "(610) 280-5120",
    embed: "https://maps.app.goo.gl/bJqFV5eXMnzTYktg7",
    website: "https://www.dccc.edu",
    high_need: false,
    addr: "443 W Boot Rd, Downingtown, PA 19335",
    rating: 4.0,
  },
  {
    id: 86,
    name: "Robert Half Staffing",
    category: "jobs",
    urgency: "general",
    description: "Professional staffing and job placement services.",
    hours: "Mon–Fri 8am–6pm",
    phone: "(484) 254-9105",
    embed: "https://maps.app.goo.gl/U8CfYgenv5G3ykZFA",
    website: "https://www.roberthalf.com",
    high_need: false,
    addr: "1300 Morris Dr Suite 101, Chesterbrook, PA 19087",
    rating: 2,
  },
  {
    id: 87,
    name: "PeopleShare Staffing",
    category: "jobs",
    urgency: "immediate",
    description: "Temporary and full-time job placement services.",
    hours: "Mon–Fri 7:30am–5:30pm",
    phone: "(610) 692-2500",
    embed: "https://maps.app.goo.gl/HURFnXh2AYJCfX8y6",
    website: "https://www.peopleshareworks.com",
    high_need: true,
    addr: "600 Willowbrook Ln, Ste 622, West Chester, PA 19382",
    rating: 4.2,
  },
  {
    id: 88,
    name: "Adecco Staffing",
    category: "jobs",
    urgency: "immediate",
    description: "Job placement and workforce solutions.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(610) 793-8071",
    embed: "https://maps.app.goo.gl/Jmoa8KVrfQwDPe7Z6",
    website: "https://www.adecco.com",
    high_need: true,
    addr: "36 Chestnut Rd A2, Paoli, PA 19301",
    rating: 5,
  },
  {
    id: 89,
    name: "Chester County Library Career Resources",
    category: "jobs",
    urgency: "general",
    description: "Resume help, job search tools, and free computer access.",
    hours: "Mon–Thu 9am–9pm, Fri–Sat 9am–5pm, Sun 12pm–5pm",
    phone: "(610) 280-2600",
    embed: "https://maps.app.goo.gl/ZxZmGZtWyFcfZagA8",
    website: "https://chescolibraries.org",
    high_need: false,
    addr: "450 Exton Square Pkwy, Exton, PA 19341",
    rating: 4.6,
  },
  {
    id: 90,
    name: "United Way Financial Stability Programs",
    category: "jobs",
    urgency: "general",
    description: "Job readiness and financial coaching.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 429-9400",
    embed: "https://maps.app.goo.gl/iZwDmMTYytnTd4dN8",
    website: "https://unitedwaychestercounty.org",
    high_need: false,
    addr: "150 John Robert Thomas Dr, Exton, PA 19341",
    rating: 4.5,
  },
  {
    id: 91,
    name: "Chester County Intermediate Unit Workforce Programs",
    category: "jobs",
    urgency: "general",
    description: "Career readiness and youth employment programs.",
    hours: "Mon–Fri 8am–4pm",
    phone: "(484) 237-5000",
    embed: "https://maps.app.goo.gl/8xaubfTUJ49omnnS6",
    website: "https://www.cciu.org",
    high_need: false,
    addr: "455 Boot Rd, Downingtown, PA 19335",
    rating: 4.4,
  },
  {
    id: 92,
    name: "Job Corps Outreach",
    category: "jobs",
    urgency: "general",
    description: "Free education and job training for young adults ages 16–24.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(800) 733-5627",
    embed: "https://maps.app.goo.gl/yUz3njKoT5xgxW5u9",
    website: "http://philadelphia.jobcorps.gov/",
    high_need: false,
    addr: "2810 S 20th St #12, Philadelphia, PA 19145",
    rating: 3.8,
  },
  {
    id: 93,
    name: "Veterans Employment Services",
    category: "jobs",
    urgency: "general",
    description: "Job placement and training for veterans.",
    hours: "Mon–Fri 8am–4pm",
    phone: "(610) 280-1010",
    embed: "https://maps.app.goo.gl/BvdJ9rxJvgZDM2oS7",
    website:
      "https://www.dli.pa.gov/Individuals/Workforce-Development/DVOP/Pages/default.aspx",
    high_need: false,
    addr: "Liberty Place, 1016 N Charlotte St, Lancaster, PA 17603",
    rating: 4.0,
  },
  {
    id: 94,
    name: "Chester County Chamber of Business & Industry",
    category: "jobs",
    urgency: "general",
    description: "Networking, job boards, and employer connections.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 725-9100",
    embed: "https://maps.app.goo.gl/67zGPxcAw3Y6GUF89",
    website: "https://www.cccbi.org",
    high_need: false,
    addr: "1600 Paoli Pike, Malvern, PA 19355",
    rating: 5,
  },
  {
    id: 95,
    name: "LinkedIn (Job Search)",
    category: "jobs",
    urgency: "general",
    description: "Professional networking and job search platform.",
    hours: "24/7 online",
    phone: "N/A",
    embed: "https://maps.app.goo.gl/Lb5QAu88HyezKHJT6",
    website: "https://www.linkedin.com/jobs",
    high_need: false,
    addr: "Chester County, PA",
    rating: 4.2,
  },
  {
    id: 96,
    name: "Indeed Job Search (Chester County)",
    category: "jobs",
    urgency: "general",
    description: "Online job search platform with local listings.",
    hours: "24/7",
    phone: "N/A",
    embed: "https://maps.app.goo.gl/Lb5QAu88HyezKHJT6",
    website: "https://www.indeed.com",
    high_need: false,
    addr: "Chester County, PA",
    rating: 4.1,
  },
  {
    id: 97,
    name: "Career Wardrobe",
    category: "jobs",
    urgency: "general",
    description: "Professional clothing and job readiness support.",
    hours: "By appointment",
    phone: "(610) 566-1776",
    embed: "https://maps.app.goo.gl/z22veSmRM5EyYbPi6",
    website: "https://careerwardrobe.org",
    high_need: false,
    addr: "413 N 4th St, Philadelphia, PA 19123",
    rating: 4.7,
  },
  {
    id: 98,
    name: "Chester County Economic Development Council",
    category: "jobs",
    urgency: "general",
    description: "Business growth and workforce development programs.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 321-8220",
    embed: "https://maps.app.goo.gl/UbMvQfxPiEqXBFbU6",
    website: "https://ccedcpa.com",
    high_need: false,
    addr: "737 Constitution Dr, Exton, PA 19341",
    rating: 4.7,
  },
  {
    id: 99,
    name: "JEVS Human Services",
    category: "jobs",
    urgency: "general",
    description: "Career training and job placement services.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(215) 854-1800",
    embed: "https://maps.app.goo.gl/5Ww9DsQC74kP9xoz7",
    website: "https://www.jevshumanservices.org",
    high_need: false,
    addr: "1845 Walnut St, Philadelphia, PA 19103",
    rating: 3.7,
  },
  {
    id: 100,
    name: "GigSmart Local Jobs",
    category: "jobs",
    urgency: "immediate",
    description: "App-based gig and flexible job opportunities.",
    hours: "24/7",
    phone: "N/A",
    embed: "https://maps.app.goo.gl/Lb5QAu88HyezKHJT6",
    website: "https://gigsmart.com",
    high_need: true,
    addr: "Chester County, PA",
    rating: 3.8,
  },
  {
    id: 101,
    name: "Snagajob Chester County",
    category: "jobs",
    urgency: "immediate",
    description: "Hourly job listings and quick applications.",
    hours: "24/7",
    phone: "N/A",
    embed: "https://maps.app.goo.gl/HsF4vSoXqGChuAU58",
    website: "https://www.snagajob.com",
    high_need: true,
    addr: "Chester County, PA",
    rating: 3.9,
  },
  {
    id: 102,
    name: "Main Line Health Careers",
    category: "jobs",
    urgency: "general",
    description: "Healthcare employment and training programs.",
    hours: "24/7 online",
    phone: "(484) 565-1000",
    embed: "https://maps.app.goo.gl/dhTH68vLeqYVFCTp9",
    website: "https://www.mainlinehealth.org/careers",
    high_need: false,
    addr: "154 Exton Square Mall, Exton, PA 19341",
    rating: 3,
  },
  {
    id: 103,
    name: "Tower Health Careers",
    category: "jobs",
    urgency: "general",
    description: "Hospital and healthcare job opportunities.",
    hours: "24/7 online",
    phone: "(610) 983-1000",
    embed: "https://maps.app.goo.gl/xkPSXJz7ajU49N8M8",
    website: "https://towerhealth.org/careers",
    high_need: false,
    addr: "1300 Schuylkill Rd, Phoenixville, PA 19460",
    rating: 3.5,
  },
  {
    id: 104,
    name: "Chester County Government Jobs",
    category: "jobs",
    urgency: "general",
    description: "Public sector employment opportunities.",
    hours: "Mon–Fri 8:30am–4:30pm",
    phone: "(610) 344-6000",
    embed: "https://maps.app.goo.gl/j1EvkbciE6n8GXrU8",
    website: "https://www.chesco.org/jobs",
    high_need: false,
    addr: "313 W Market St, West Chester, PA 19382",
    rating: 3.7,
  },
  {
    id: 105,
    name: "USAJobs (Federal Jobs)",
    category: "jobs",
    urgency: "general",
    description: "Federal employment opportunities in the region.",
    hours: "24/7",
    phone: "N/A",
    embed: "https://maps.app.goo.gl/j1EvkbciE6n8GXrU8",
    website: "https://www.usajobs.gov",
    high_need: false,
    addr: "Chester County, PA",
    rating: 4.0,
  },
  {
    id: 106,
    name: "Wawa Careers (Regional HQ)",
    category: "jobs",
    urgency: "immediate",
    description: "Retail and corporate job opportunities.",
    hours: "24/7 online",
    phone: "(610) 358-8000",
    embed: "https://maps.app.goo.gl/j1EvkbciE6n8GXrU8",
    website: "https://www.wawa.com/careers",
    high_need: true,
    addr: "260 W Baltimore Pike, Wawa, PA 19063",
    rating: 4.2,
  },
  {
    id: 107,
    name: "Amazon Jobs (Regional Warehouses)",
    category: "jobs",
    urgency: "immediate",
    description: "Warehouse and logistics job opportunities.",
    hours: "24/7 online",
    phone: "N/A",
    embed: "https://maps.app.goo.gl/j1EvkbciE6n8GXrU8",
    website: "https://www.amazon.jobs",
    high_need: true,
    addr: "Chester County, PA",
    rating: 3.6,
  },
  {
    id: 108,
    name: "UPS Jobs Chester County",
    category: "jobs",
    urgency: "immediate",
    description: "Package handling and delivery jobs.",
    hours: "Varies by shift",
    phone: "N/A",
    embed: "https://maps.app.goo.gl/j1EvkbciE6n8GXrU8",
    website: "https://www.jobs-ups.com",
    high_need: true,
    addr: "Chester County, PA",
    rating: 3.5,
  },

  // ─────────────────────────────────────────────
  // EDUCATION
  // ─────────────────────────────────────────────
  {
    id: 109,
    name: "Chester County Library System",
    category: "education",
    urgency: "general",
    description:
      "Free access to books, tutoring, ESL classes, and digital resources.",
    hours: "Mon–Thu 9am–9pm, Fri–Sat 9am–5pm, Sun 12pm–5pm",
    phone: "(610) 280-2600",
    embed: "https://maps.app.goo.gl/j1EvkbciE6n8GXrU8",
    website: "https://chescolibraries.org",
    high_need: false,
    addr: "Chester County, PA",
    rating: 4.6,
  },
  {
    id: 110,
    name: "Chester County Intermediate Unit (CCIU)",
    category: "education",
    urgency: "general",
    description:
      "Educational services, special education, and workforce training programs.",
    hours: "Mon–Fri 8am–4pm",
    phone: "(484) 237-5000",
    embed: "https://maps.app.goo.gl/5BSgBg64jDD7ncM4A",
    website: "https://www.cciu.org",
    high_need: false,
    addr: "455 Boot Rd, Downingtown, PA 19335",
    rating: 4.4,
  },
  {
    id: 111,
    name: "Delaware County Community College (Exton Center)",
    category: "education",
    urgency: "general",
    description:
      "Associate degrees, certifications, and continuing education programs.",
    hours: "Mon–Fri 8am–6pm (Permanently Closed)",
    phone: "(610) 280-5120",
    embed: "https://maps.app.goo.gl/ASPZbndd8VsnDX1U8",
    website: "https://www.dccc.edu",
    high_need: false,
    addr: "Whiteland Business Park, 906 Springdale Dr, Exton, PA 19341",
    rating: 4.0,
  },
  {
    id: 112,
    name: "West Chester University",
    category: "education",
    urgency: "general",
    description: "Undergraduate, graduate, and continuing education programs.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(610) 436-1000",
    embed: "https://maps.app.goo.gl/VzBW55hp56JAzqAq6",
    website: "https://www.wcupa.edu",
    high_need: false,
    addr: "700 S High St, West Chester, PA 19383",
    rating: 4.1,
  },
  {
    id: 113,
    name: "Technical College High School (TCHS)",
    category: "education",
    urgency: "general",
    description:
      "Career and technical education programs for high school students and adults.",
    hours: "Mon–Fri 7:30am–3pm",
    phone: "(610) 692-1964",
    embed: "https://maps.app.goo.gl/nmhTExcDS7Zu7wj7A",
    website: "https://www.cciu.org/tchs",
    high_need: false,
    addr: "443 W Boot Rd, Downingtown, PA 19335",
    rating: 4.3,
  },
  {
    id: 114,
    name: "Chester County OIC Education Programs",
    category: "education",
    urgency: "general",
    description: "GED prep, adult literacy, and workforce education.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 692-2344",
    embed: "https://maps.app.goo.gl/FhX9DN1kuq6MSsQt8",
    website: "https://ccoic.org",
    high_need: false,
    addr: "22 N 5th Ave, Coatesville, PA 19320",
    rating: 4.7,
  },
  {
    id: 115,
    name: "PA CareerLink Training Programs",
    category: "education",
    urgency: "general",
    description:
      "Career training, certifications, and skill-building programs.",
    hours: "Mon–Fri 8:30am–4:30pm",
    phone: "(610) 280-1010",
    embed: "https://maps.app.goo.gl/B4tnMY75w9ZKdBdw5",
    website: "https://www.pacareerlinkchesco.org",
    high_need: false,
    addr: "479 Thomas Jones Way, Ste 500, Exton, PA 19341",
    rating: 4.3,
  },
  {
    id: 116,
    name: "Brandywine Valley SPCA Humane Education",
    category: "education",
    urgency: "general",
    description:
      "Educational programs focused on animal welfare and community engagement.",
    hours: "Varies by program",
    phone: "(610) 692-6113",
    embed: "https://maps.app.goo.gl/GKdFHM9ALX2XEot68",
    website: "https://bvspca.org",
    high_need: false,
    addr: "1212 Phoenixville Pike, West Chester, PA 19380",
    rating: 4.6,
  },
  {
    id: 117,
    name: "YMCA of Greater Brandywine Education Programs",
    category: "education",
    urgency: "general",
    description: "After-school programs, tutoring, and youth development.",
    hours: "Mon–Fri 5:30am–10pm, Sat 7am–8pm, Sun 9am–6pm",
    phone: "(610) 363-9622",
    embed: "https://maps.app.goo.gl/Wx8WfCk96yGScKt79",
    website: "https://ymcagbw.org",
    high_need: false,
    addr: "1 E Chestnut St, West Chester, PA 19380",
    rating: 3.9,
  },
  {
    id: 118,
    name: "Chester County Historical Society Education",
    category: "education",
    urgency: "general",
    description:
      "History education programs, exhibits, and research resources.",
    hours: "Tue–Sat 10am–4pm",
    phone: "(610) 692-4800",
    embed: "https://maps.app.goo.gl/28hkWgSFu6zSP3g59",
    website: "https://mycchc.org",
    high_need: false,
    addr: "225 N High St, West Chester, PA 19380",
    rating: 4.7,
  },
  {
    id: 119,
    name: "Art Association of Chester County",
    category: "education",
    urgency: "general",
    description: "Art classes, workshops, and community education programs.",
    hours: "Mon–Sat 10am–4pm",
    phone: "(610) 696-5600",
    embed: "https://maps.app.goo.gl/vDKaWoHQfKUM4RiU7",
    website: "https://chestercountyarts.org",
    high_need: false,
    addr: "100 N Bradford Ave, West Chester, PA 19382",
    rating: 4.8,
  },
  {
    id: 120,
    name: "Penn State Extension Chester County",
    category: "education",
    urgency: "general",
    description:
      "Workshops and educational programs in agriculture, health, and youth development.",
    hours: "Mon–Fri 8:30am–4:30pm",
    phone: "(610) 696-3500",
    embed: "https://maps.app.goo.gl/Y2QmKC9LPkDnvPqX7",
    website: "https://extension.psu.edu/chester-county",
    high_need: false,
    addr: "601 Westtown Rd, Ste 380, West Chester, PA 19382",
    rating: 4.3,
  },
  {
    id: 121,
    name: "Stroud Water Research Center Education",
    category: "education",
    urgency: "general",
    description: "Environmental education and science programs.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 268-2153",
    embed: "https://maps.app.goo.gl/9AhLaKLnJs4u8RTS9",
    website: "https://www.stroudcenter.org",
    high_need: false,
    addr: "970 Spencer Rd, Avondale, PA 19311",
    rating: 5,
  },
  {
    id: 122,
    name: "The Garage Community & Youth Center",
    category: "education",
    urgency: "general",
    description: "After-school programs, mentoring, and youth education.",
    hours: "Mon–Fri 3pm–8pm",
    phone: "(610) 692-5550",
    embed: "https://maps.app.goo.gl/bwL4DGTcvpCNPfM7A",
    website: "https://thegarageyouthcenter.org",
    high_need: false,
    addr: "121 Pennsylvania Ave, Avondale, PA 19311",
    rating: 5,
  },
  {
    id: 123,
    name: "Chester County Futures",
    category: "education",
    urgency: "general",
    description: "College readiness and academic support for students.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 524-0005",
    embed: "https://maps.app.goo.gl/RnyhtThgWoBsCsok7",
    website: "https://ccfutures.org",
    high_need: false,
    addr: "50 S 1st Ave Suite 105, Coatesville, PA 19320",
    rating: 5,
  },
  {
    id: 124,
    name: "La Comunidad Hispana Education Programs",
    category: "education",
    urgency: "general",
    description: "Bilingual education, ESL, and youth programs.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(610) 444-7550",
    embed: "https://maps.app.goo.gl/fVjWkP8Mvc5oWW6X9",
    website: "https://lchcommunityhealth.org",
    high_need: false,
    addr: "731 W Cypress St, Kennett Square, PA 19348",
    rating: 3.8,
  },
  {
    id: 125,
    name: "Kennett Library Learning Programs",
    category: "education",
    urgency: "general",
    description: "Workshops, tutoring, and community education events.",
    hours: "Mon–Thu 9am–8pm, Fri–Sat 9am–5pm",
    phone: "(610) 444-2702",
    embed: "https://maps.app.goo.gl/8BzQQbhGRpqpuxcf7",
    website: "https://kennettlibrary.org",
    high_need: false,
    addr: "320 E State St, Kennett Square, PA 19348",
    rating: 4.6,
  },
  {
    id: 126,
    name: "Phoenixville Public Library Programs",
    category: "education",
    urgency: "general",
    description: "Educational workshops, literacy programs, and tutoring.",
    hours: "Mon–Thu 9am–8pm, Fri–Sat 9am–5pm",
    phone: "(610) 933-3013",
    embed: "https://maps.app.goo.gl/maqmUcko6AgY5vNf9",
    website: "https://phoenixvillelibrary.org",
    high_need: false,
    addr: "183 2nd Ave, Phoenixville, PA 19460",
    rating: 4.4,
  },
  {
    id: 127,
    name: "Coatesville Area Public Library Programs",
    category: "education",
    urgency: "general",
    description: "After-school tutoring, reading programs, and workshops.",
    hours: "Mon–Thu 10am–8pm, Fri–Sat 10am–5pm",
    phone: "(610) 384-4115",
    embed: "https://maps.app.goo.gl/Yho43FFBwW5AMRfQ9",
    website: "https://www.coatesvillelibrary.org",
    high_need: false,
    addr: "501 E Lincoln Hwy, Coatesville, PA 19320",
    rating: 4.5,
  },
  {
    id: 128,
    name: "Tredyffrin Public Library Programs",
    category: "education",
    urgency: "general",
    description: "STEM programs, tutoring, and educational workshops.",
    hours: "Mon–Thu 9am–9pm, Fri 9am–6pm, Sat 9am–5pm",
    phone: "(610) 688-7092",
    embed: "https://maps.app.goo.gl/6xMHGJWdZYESyAZ4A",
    website: "https://tredyffrinlibraries.org",
    high_need: false,
    addr: "582 Upper Gulph Rd, Strafford, PA 19087",
    rating: 4.8,
  },
  {
    id: 129,
    name: "Immaculata University Continuing Education",
    category: "education",
    urgency: "general",
    description: "Adult degree completion and certificate programs.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 647-4400",
    embed: "https://maps.app.goo.gl/DbwdBii963vJRTft5",
    website: "https://www.immaculata.edu",
    high_need: false,
    addr: "1145 King Rd, Immaculata, PA 19345",
    rating: 4.5,
  },
  {
    id: 130,
    name: "Cheyney University Outreach Programs",
    category: "education",
    urgency: "general",
    description: "Community education and workforce readiness programs.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 399-2000",
    embed: "https://maps.app.goo.gl/tzP553q4PiFTWPWU8",
    website: "https://www.cheyney.edu",
    high_need: false,
    addr: "1837 University Cir, Cheyney, PA 19319",
    rating: 3.8,
  },
];
export const EMERGENCY = [
  {
    emoji: <FaHouse></FaHouse>,
    title: "Night Shelter",
    description: "Chester County Night Shelter — walk-in 5pm nightly",
    phone: "(610) 696-6877",
    cat: "Housing",
  },
  {
    emoji: <MdOutlineFastfood />,
    title: "Hot Meals Daily",
    description: "Phoenixville Good Samaritan — hot lunch 11:30am every day",
    phone: "(610) 933-0741",
    cat: "Food",
  },
  {
    emoji: <FaPhoneAlt></FaPhoneAlt>,
    title: "Crisis Line 24/7",
    description: "Crisis Text Line — text HOME to 741741",
    phone: "741741 (text)",
    cat: "Mental Health",
  },
  {
    emoji: <LuSiren></LuSiren>,
    title: "DV Crisis Shelter",
    description: "YWCA confidential emergency shelter — available now",
    phone: "(610) 692-7273",
    cat: "Safety",
  },
];
