export const RESOURCESCHAT = [
  {
    id: 1,
    name: "Chester County Hospital",
    category: "health",
    urgency: "immediate",
    description: "Full-service hospital providing emergency care, surgery, maternity, and specialty services.",
    hours: "24/7",
    phone: "(610) 431-5000",
    embed: "",
    website:
      "https://www.pennmedicine.org/locations/entity/chester-county-hospital",
    high_need: true,
    addr: "701 E Marshall St, West Chester PA",
  },
  {
    id: 2,
    name: "Paoli Hospital",
    category: "health",
    urgency: "immediate",
    description: "Acute care hospital offering emergency, cardiac, and surgical services.",
    hours: "24/7",
    phone: "(484) 565-1000",
    embed: "",
    website: "https://www.mainlinehealth.org/locations/paoli-hospital",
    high_need: true,
    addr: "255 W Lancaster Ave, Paoli PA",
  },
  {
    id: 4,
    name: "Penn Medicine Southern Chester County",
    category: "health",
    urgency: "immediate",
    description: "Emergency department and outpatient services in southern Chester County.",
    hours: "24/7",
    phone: "(610) 869-1000",
    embed: "",
    website: "https://www.pennmedicine.org",
    high_need: true,
    addr: "455 Woodview Rd, West Grove PA",
  },
  {
    id: 5,
    name: "ChesPenn Health Services",
    category: "health",
    urgency: "general",
    description: "Community health center offering primary care, dental, and behavioral health.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(610) 383-3888",
    embed: "",
    website: "https://chespenn.org",
    high_need: false,
    addr: "744 E Lincoln Hwy, Coatesville PA",
  },
  {
    id: 6,
    name: "Community Volunteers in Medicine",
    category: "health",
    urgency: "general",
    description: "Free medical and dental care for uninsured adults.",
    hours: "Mon–Thu 9am–5pm",
    phone: "(610) 836-5990",
    embed: "",
    website: "https://cvim.org",
    high_need: false,
    addr: "300 B Lawrence Dr, West Chester PA",
  },
  {
    id: 7,
    name: "La Comunidad Hispana Health Center",
    category: "health",
    urgency: "general",
    description: "Bilingual primary care, women's health, and pediatric services.",
    hours: "Mon–Fri 8am–6pm",
    phone: "(610) 444-7550",
    embed: "",
    website: "https://lchcommunityhealth.org",
    high_need: false,
    addr: "731 W Cypress St, Kennett Square PA",
  },
  {
    id: 8,
    name: "Phoenixville Hospital",
    category: "health",
    urgency: "immediate",
    description: "Emergency care, surgery, and inpatient services.",
    hours: "24/7",
    phone: "(610) 983-1000",
    embed: "",
    website: "https://towerhealth.org",
    high_need: true,
    addr: "140 Nutt Rd, Phoenixville PA",
  },
  {
    id: 9,
    name: "Devereux Advanced Behavioral Health",
    category: "health",
    urgency: "general",
    description: "Mental health, autism, and behavioral health services.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(610) 431-8900",
    embed: "",
    website: "https://www.devereux.org",
    high_need: false,
    addr: "655 Sugartown Rd, Malvern PA",
  },
  {
    id: 10,
    name: "Penn Medicine Exton",
    category: "health",
    urgency: "general",
    description: "Outpatient center with primary care, imaging, and specialty services.",
    hours: "Mon–Fri 7am–7pm",
    phone: "(484) 565-8600",
    embed: "",
    website: "https://www.pennmedicine.org",
    high_need: false,
    addr: "145 King of Prussia Rd, Exton PA",
  },
  {
    id: 11,
    name: "Chester County Health Department",
    category: "health",
    urgency: "general",
    description: "Public health services including immunizations and health screenings.",
    hours: "Mon–Fri 8:30–4:30",
    phone: "(610) 344-6225",
    embed: "",
    website: "https://www.chesco.org",
    high_need: false,
    addr: "601 Westtown Rd, West Chester PA",
  },
  {
    id: 12,
    name: "Main Line Health Center Exton",
    category: "health",
    urgency: "general",
    description: "Primary care, specialty care, and outpatient services.",
    hours: "Mon–Fri 8am–6pm",
    phone: "(484) 565-1293",
    embed: "",
    website: "https://www.mainlinehealth.org",
    high_need: false,
    addr: "154 Exton Square Pkwy, Exton PA",
  },
  {
    id: 13,
    name: "Tower Health Urgent Care Downingtown",
    category: "health",
    urgency: "immediate",
    description: "Walk-in urgent care for minor injuries and illnesses.",
    hours: "Daily 8am–8pm",
    phone: "(484) 593-3100",
    embed: "",
    website: "https://towerhealth.org",
    high_need: true,
    addr: "150 E Pennsylvania Ave, Downingtown PA",
  },
  {
    id: 14,
    name: "Patient First Downingtown",
    category: "health",
    urgency: "immediate",
    description: "Urgent care, primary care, and lab services.",
    hours: "Daily 8am–10pm",
    phone: "(610) 873-6400",
    embed: "",
    website: "https://www.patientfirst.com",
    high_need: true,
    addr: "150 E Pennsylvania Ave, Downingtown PA",
  },
  {
    id: 15,
    name: "AFC Urgent Care West Chester",
    category: "health",
    urgency: "immediate",
    description: "Walk-in urgent care with extended hours.",
    hours: "Daily 8am–8pm",
    phone: "(484) 999-0211",
    embed: "",
    website: "https://www.afcurgentcare.com",
    high_need: true,
    addr: "510 E Gay St, West Chester PA",
  },
  {
    id: 16,
    name: "Holcomb Behavioral Health Systems",
    category: "health",
    urgency: "general",
    description: "Mental health and substance use treatment services.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 363-1488",
    embed: "",
    website: "https://www.chimes.org",
    high_need: false,
    addr: "467 Creamery Way, Exton PA",
  },
  {
    id: 17,
    name: "Gaudenzia Coatesville",
    category: "health",
    urgency: "immediate",
    description: "Addiction treatment and recovery services.",
    hours: "24/7",
    phone: "(610) 383-9600",
    embed: "",
    website: "https://www.gaudenzia.org",
    high_need: true,
    addr: "31 S 10th Ave, Coatesville PA",
  },
  {
    id: 18,
    name: "Chester County Eye Care",
    category: "health",
    urgency: "general",
    description: "Vision care, exams, and treatment services.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 696-1230",
    embed: "",
    website: "https://www.chestercountyeyecare.com/",
    high_need: false,
    addr: "915 Old Fern Hill Rd, West Chester PA",
  },
  {
    id: 19,
    name: "Penn Care at Home",
    category: "health",
    urgency: "general",
    description: "Home health and hospice care services.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(800) 789-7366",
    embed: "",
    website: "https://www.pennmedicine.org",
    high_need: false,
    addr: "Chester County, PA",
  },
  {
    id: 20,
    name: "Chester County Dental Arts",
    category: "health",
    urgency: "general",
    description: "Comprehensive dental care services.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 431-4444",
    embed: "",
    website: "https://www.chestercountydentalarts.com/",
    high_need: false,
    addr: "West Chester PA",
  },
  {
    id: 21,
    name: "Penn Medicine West Chester Pike Health Center",
    category: "health",
    urgency: "general",
    description: "Primary and specialty outpatient care services.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(610) 696-2850",
    embed: "",
    website: "https://www.pennmedicine.org",
    high_need: false,
    addr: "West Chester PA",
  },
  {
    id: 22,
    name: "Nemours Children's Health Exton",
    category: "health",
    urgency: "general",
    description: "Pediatric primary and specialty care.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(610) 594-9000",
    embed: "",
    website: "https://www.nemours.org",
    high_need: false,
    addr: "466 W Lincoln Hwy, Exton PA",
  },
  {
    id: 23,
    name: "Chester County OB/GYN Associates",
    category: "health",
    urgency: "general",
    description: "Women’s health, prenatal, and gynecological services.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(610) 692-3434",
    embed: "",
    website:
      "https://axiawh.com/locations/chester-county-ob-gyn-of-west-chester/",
    high_need: false,
    addr: "915 Old Fern Hill Rd, West Chester PA",
  },
  {
    id: 24,
    name: "Pennsylvania Psychiatric Institute (Outreach)",
    category: "health",
    urgency: "general",
    description: "Mental health evaluations and psychiatric care referrals.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(717) 782-3131",
    embed: "",
    website: "https://ppimhs.org/",
    high_need: false,
    addr: "Chester County, PA",
  },
  {
    id: 25,
    name: "Better Beginnings Maternal Care",
    category: "health",
    urgency: "general",
    description: "Maternal health, prenatal education, and support services.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 344-5370",
    embed: "",
    website:
      "https://www.pennmedicine.org/locations/entity/chester-county-hospital?redirect=1&referrer=pennmed&source=fsu",
    high_need: false,
    addr: "West Chester PA",
  },
  {
    id: 26,
    name: "Chester County Immunization Clinic",
    category: "health",
    urgency: "general",
    description: "Low-cost and free vaccines for children and adults.",
    hours: "By appointment",
    phone: "(610) 344-6225",
    embed: "",
    website: "https://www.chesco.org",
    high_need: false,
    addr: "601 Westtown Rd, West Chester PA",
  },
  {
    id: 27,
    name: "Main Line Health Behavioral Services",
    category: "health",
    urgency: "general",
    description: "Outpatient therapy, psychiatry, and addiction treatment.",
    hours: "Mon–Fri 8am–6pm",
    phone: "(484) 565-1130",
    embed: "",
    website: "https://www.mainlinehealth.org",
    high_need: false,
    addr: "Paoli PA",
  },
  {
    id: 28,
    name: "Tower Health Primary Care Coatesville",
    category: "health",
    urgency: "general",
    description: "Primary care and chronic disease management.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(610) 383-8300",
    embed: "",
    website: "https://towerhealth.org",
    high_need: false,
    addr: "Coatesville PA",
  },
  {
    id: 29,
    name: "Penn Medicine Dermatology West Chester",
    category: "health",
    urgency: "general",
    description: "Skin care, dermatology, and treatment services.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(610) 436-4444",
    embed: "",
    website: "https://www.pennmedicine.org/specialties/dermatology",
    high_need: false,
    addr: "West Chester PA",
  },
  {
    id: 30,
    name: "Chester County Cancer Center",
    category: "health",
    urgency: "immediate",
    description: "Oncology services including chemotherapy and support care.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(610) 738-2500",
    embed: "",
    website:
      "https://www.pennmedicine.org/practices/abramson-cancer-center-west-chester",
    high_need: true,
    addr: "Suite 101, 440 East Marshall Street, West Chester, PA, 19380",
  },
  {
    id: 31,
    name: "Penn Medicine Cardiology",
    category: "health",
    urgency: "general",
    description: "Heart care, diagnostics, and cardiology services.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(484) 565-8600",
    embed: "",
    website:
      "https://www.pennmedicine.org/practices/chester-county-cardiology-associates-west-grove",
    high_need: false,
    addr: "Suite 205, 455 West Woodview Road, West Grove, PA, 19390",
  },
  {
    id: 32,
    name: "Chester County Neurology Associates",
    category: "health",
    urgency: "general",
    description: "Neurological evaluations and treatment services.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 696-1234",
    embed: "",
    website: "https://www.pennmedicine.org/practices/neurology-westtown",
    high_need: false,
    addr: "Suite 210, 200 Willowbrook Lane, West Chester, PA, 19382",
  },
  {
    id: 33,
    name: "Penn Medicine Orthopedics",
    category: "health",
    urgency: "general",
    description: "Bone, joint, and sports injury treatment.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(610) 444-0500",
    embed: "",
    website: "https://www.pennmedicine.org/specialties/orthopaedics",
    high_need: false,
    addr: "Chadds Ford PA",
  },
  {
    id: 34,
    name: "Chester County Physical Therapy",
    category: "health",
    urgency: "general",
    description: "Rehabilitation and physical therapy services.",
    hours: "Mon–Fri 7am–6pm",
    phone: "(610) 430-9000",
    embed: "",
    website: "#",
    high_need: false,
    addr: "West Chester PA",
  },
  {
    id: 35,
    name: "Brandywine Valley Counseling Services",
    category: "health",
    urgency: "general",
    description: "Mental health counseling and therapy.",
    hours: "Mon–Fri 9am–6pm",
    phone: "(610) 383-9600",
    embed: "",
    website: "#",
    high_need: false,
    addr: "Coatesville PA",
  },
  {
    id: 36,
    name: "Penn Medicine Gastroenterology",
    category: "health",
    urgency: "general",
    description: "Digestive health and GI treatment services.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(610) 738-2400",
    embed: "",
    website: "#",
    high_need: false,
    addr: "West Chester PA",
  },
  {
    id: 37,
    name: "Chester County Podiatry Center",
    category: "health",
    urgency: "general",
    description: "Foot and ankle care services.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 692-1118",
    embed: "",
    website: "#",
    high_need: false,
    addr: "West Chester PA",
  },
  {
    id: 38,
    name: "Penn Medicine Imaging Exton",
    category: "health",
    urgency: "general",
    description: "Radiology and diagnostic imaging services.",
    hours: "Mon–Fri 7am–6pm",
    phone: "(484) 565-8600",
    embed: "",
    website: "#",
    high_need: false,
    addr: "Exton PA",
  },
  {
    id: 39,
    name: "Chester County Sleep Center",
    category: "health",
    urgency: "general",
    description: "Sleep studies and treatment for sleep disorders.",
    hours: "By appointment",
    phone: "(610) 738-2300",
    embed: "",
    website: "#",
    high_need: false,
    addr: "West Chester PA",
  },
  {
    id: 40,
    name: "Penn Medicine Pain Management",
    category: "health",
    urgency: "general",
    description: "Chronic pain evaluation and treatment services.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(610) 738-2600",
    embed: "",
    website: "#",
    high_need: false,
    addr: "West Chester PA",
  },
  {
    id: 41,
    name: "Chester County Food Bank",
    category: "food",
    urgency: "immediate",
    description: "Countywide food distribution, mobile pantries, and meal programs.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 873-6000",
    embed: "",
    website: "https://chestercountyfoodbank.org",
    high_need: true,
    addr: "650 Pennsylvania Dr, Exton PA",
  },
  {
    id: 42,
    name: "West Chester Food Cupboard",
    category: "food",
    urgency: "general",
    description: "Supplemental groceries for residents, no appointment required on select days.",
    hours: "Tue & Fri 10am–1pm",
    phone: "(610) 696-6877",
    embed: "",
    website: "https://westchesterfoodcupboard.org",
    high_need: false,
    addr: "228 W Gay St, West Chester PA",
  },
  {
    id: 43,
    name: "Phoenixville Area Community Services (PACS)",
    category: "food",
    urgency: "general",
    description: "Food pantry and emergency assistance for local residents.",
    hours: "Mon–Fri 9am–3pm",
    phone: "(610) 933-1105",
    embed: "",
    website: "https://pacsphx.org",
    high_need: false,
    addr: "257 Church St, Phoenixville PA",
  },
  {
    id: 44,
    name: "Kennett Area Community Service",
    category: "food",
    urgency: "general",
    description: "Food pantry and emergency financial assistance.",
    hours: "Mon–Fri 9am–4pm",
    phone: "(610) 925-3556",
    embed: "",
    website: "https://kacsimpact.org/",
    high_need: false,
    addr: "136 W Cedar St, Kennett Square PA",
  },
  {
    id: 45,
    name: "Oxford Neighborhood Services Center",
    category: "food",
    urgency: "general",
    description: "Food pantry and support services for families.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 932-8557",
    embed: "",
    website: "#",
    high_need: false,
    addr: "35 N 3rd St, Oxford PA",
  },
  {
    id: 46,
    name: "Coatesville Salvation Army Food Pantry",
    category: "food",
    urgency: "immediate",
    description: "Emergency food assistance and hot meals.",
    hours: "Mon–Fri 9am–4pm",
    phone: "(610) 384-2954",
    embed: "",
    website: "https://salvationarmy.org",
    high_need: true,
    addr: "250 E Lincoln Hwy, Coatesville PA",
  },
  {
    id: 47,
    name: "Lord’s Pantry of Downingtown",
    category: "food",
    urgency: "general",
    description: "Weekly food distribution for individuals and families.",
    hours: "Sat mornings",
    phone: "(610) 873-1149",
    embed: "",
    website: "#",
    high_need: false,
    addr: "Downingtown PA",
  },
  {
    id: 48,
    name: "Good Samaritan Services Phoenixville",
    category: "food",
    urgency: "immediate",
    description: "Daily hot meals and food pantry access.",
    hours: "Daily 11:30am–1pm",
    phone: "(610) 933-0741",
    embed: "",
    website: "https://goodsamservices.org",
    high_need: true,
    addr: "265 Church St, Phoenixville PA",
  },
  {
    id: 49,
    name: "St. Agnes Day Room",
    category: "food",
    urgency: "immediate",
    description: "Free meals and support services for those in need.",
    hours: "Mon–Fri 9am–2pm",
    phone: "(610) 696-8746",
    embed: "",
    website: "#",
    high_need: true,
    addr: "233 W Gay St, West Chester PA",
  },
  {
    id: 50,
    name: "Brandywine Valley Church Food Pantry",
    category: "food",
    urgency: "general",
    description: "Community food pantry open weekly.",
    hours: "Wed evenings",
    phone: "(610) 383-8822",
    embed: "",
    website: "#",
    high_need: false,
    addr: "Honey Brook PA",
  },
  {
    id: 51,
    name: "Chester County Senior Center Meals",
    category: "food",
    urgency: "general",
    description: "Congregate and home-delivered meals for seniors.",
    hours: "Mon–Fri",
    phone: "(610) 344-6350",
    embed: "",
    website: "https://chesco.org",
    high_need: false,
    addr: "Chester County, PA",
  },
  {
    id: 52,
    name: "Meals on Wheels Chester County",
    category: "food",
    urgency: "general",
    description: "Home-delivered meals for seniors and disabled residents.",
    hours: "Mon–Fri",
    phone: "(610) 430-8500",
    embed: "",
    website: "#",
    high_need: false,
    addr: "West Chester PA",
  },
  {
    id: 53,
    name: "St. Patrick’s Food Cupboard",
    category: "food",
    urgency: "general",
    description: "Monthly food distribution for local families.",
    hours: "By schedule",
    phone: "(610) 696-2339",
    embed: "",
    website: "#",
    high_need: false,
    addr: "Malvern PA",
  },
  {
    id: 54,
    name: "Calvary Fellowship Food Pantry",
    category: "food",
    urgency: "general",
    description: "Food assistance and grocery distribution.",
    hours: "Weekly",
    phone: "(610) 384-8744",
    embed: "",
    website: "#",
    high_need: false,
    addr: "Downingtown PA",
  },
  {
    id: 55,
    name: "Avondale Food Pantry",
    category: "food",
    urgency: "general",
    description: "Local pantry serving southern Chester County.",
    hours: "Weekly",
    phone: "(610) 268-8466",
    embed: "",
    website: "#",
    high_need: false,
    addr: "Avondale PA",
  },
  {
    id: 56,
    name: "St. Rocco Food Pantry",
    category: "food",
    urgency: "general",
    description: "Community food support for families in need.",
    hours: "Weekly",
    phone: "(610) 384-2481",
    embed: "",
    website: "#",
    high_need: false,
    addr: "Avondale PA",
  },
  {
    id: 57,
    name: "West Grove United Methodist Pantry",
    category: "food",
    urgency: "general",
    description: "Food assistance for local residents.",
    hours: "Weekly",
    phone: "(610) 869-9334",
    embed: "",
    website: "#",
    high_need: false,
    addr: "West Grove PA",
  },
  {
    id: 58,
    name: "Parkesburg Point Food Pantry",
    category: "food",
    urgency: "general",
    description: "Food and essentials distribution.",
    hours: "Weekly",
    phone: "(610) 857-3399",
    embed: "",
    website: "#",
    high_need: false,
    addr: "Parkesburg PA",
  },
  {
    id: 59,
    name: "Downingtown Area Food Bank",
    category: "food",
    urgency: "general",
    description: "Food distribution for families in need.",
    hours: "Weekly",
    phone: "(610) 873-1149",
    embed: "",
    website: "#",
    high_need: false,
    addr: "Downingtown PA",
  },
  {
    id: 60,
    name: "Honey Brook Food Pantry",
    category: "food",
    urgency: "general",
    description: "Local food assistance for residents.",
    hours: "Weekly",
    phone: "(610) 273-2848",
    embed: "",
    website: "#",
    high_need: false,
    addr: "Honey Brook PA",
  },
  {
    id: 61,
    name: "Chester County Housing Authority",
    category: "housing",
    urgency: "general",
    description: "Section 8 vouchers, public housing, and rental assistance programs.",
    hours: "Mon–Fri 8:30am–4:30pm",
    phone: "(610) 436-9200",
    embed: "",
    website: "https://www.haccnet.org",
    high_need: false,
    addr: "30 W Barnard St, West Chester PA",
  },
  {
    id: 62,
    name: "Good Samaritan Services",
    category: "housing",
    urgency: "immediate",
    description: "Emergency shelter, transitional housing, and homelessness prevention.",
    hours: "24/7",
    phone: "(610) 933-0741",
    embed: "",
    website: "https://goodsamservices.org",
    high_need: true,
    addr: "35 Hall St, Phoenixville PA",
  },
  {
    id: 63,
    name: "Bridge of Hope Chester County",
    category: "housing",
    urgency: "general",
    description: "Transitional housing and support for single mothers facing homelessness.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 280-0280",
    embed: "",
    website: "https://bridgeofhopeinc.org",
    high_need: false,
    addr: "Exton PA",
  },
  {
    id: 64,
    name: "Safe Harbor of Chester County",
    category: "housing",
    urgency: "immediate",
    description: "Emergency shelter and supportive services for men experiencing homelessness.",
    hours: "24/7",
    phone: "(610) 692-6550",
    embed: "",
    website: "https://safeharborofcc.org",
    high_need: true,
    addr: "20 N Matlack St, West Chester PA",
  },
  {
    id: 65,
    name: "Domestic Violence Center of Chester County",
    category: "housing",
    urgency: "immediate",
    description: "Emergency shelter and housing support for survivors of domestic violence.",
    hours: "24/7 hotline",
    phone: "(610) 431-1430",
    embed: "",
    website: "https://dvccc.com",
    high_need: true,
    addr: "West Chester PA",
  },
  {
    id: 66,
    name: "Coatesville Housing Authority",
    category: "housing",
    urgency: "general",
    description: "Affordable housing and rental assistance programs.",
    hours: "Mon–Fri 8am–4pm",
    phone: "(610) 384-5380",
    embed: "",
    website: "#",
    high_need: false,
    addr: "Hollow Rd, Coatesville PA",
  },
  {
    id: 67,
    name: "Phoenixville Housing Authority",
    category: "housing",
    urgency: "general",
    description: "Public housing and housing choice voucher programs.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 933-5338",
    embed: "",
    website: "#",
    high_need: false,
    addr: "400 Franklin Ave, Phoenixville PA",
  },
  {
    id: 68,
    name: "Friends Association for Care & Protection",
    category: "housing",
    urgency: "immediate",
    description: "Emergency family shelter and homelessness prevention services.",
    hours: "24/7",
    phone: "(610) 431-3598",
    embed: "",
    website: "https://friendsassoc.org",
    high_need: true,
    addr: "113 W Chestnut St, West Chester PA",
  },
  {
    id: 69,
    name: "Housing Partnership of Chester County",
    category: "housing",
    urgency: "general",
    description: "Housing counseling, foreclosure prevention, and financial education.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 518-1522",
    embed: "",
    website: "https://housingpartnershipcc.org",
    high_need: false,
    addr: "West Chester PA",
  },
  {
    id: 70,
    name: "Chester County Department of Human Services Housing Support",
    category: "housing",
    urgency: "general",
    description: "Emergency rental assistance and housing stabilization programs.",
    hours: "Mon–Fri 8:30am–4:30pm",
    phone: "(610) 344-6225",
    embed: "",
    website: "https://www.chesco.org",
    high_need: false,
    addr: "601 Westtown Rd, West Chester PA",
  },
  {
    id: 71,
    name: "Open Hearth Inc.",
    category: "housing",
    urgency: "general",
    description: "Transitional and permanent housing for single men.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 430-3816",
    embed: "",
    website: "https://theopenhearth.org",
    high_need: false,
    addr: "313 S Matlack St, West Chester PA",
  },
  {
    id: 72,
    name: "Oxford Area Neighborhood Services Center",
    category: "housing",
    urgency: "general",
    description: "Rental assistance and housing support services.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 932-8557",
    embed: "",
    website: "#",
    high_need: false,
    addr: "35 N 3rd St, Oxford PA",
  },
  {
    id: 73,
    name: "Kennett Area Community Service Housing Assistance",
    category: "housing",
    urgency: "general",
    description: "Emergency housing assistance and rent support.",
    hours: "Mon–Fri 9am–4pm",
    phone: "(610) 925-3556",
    embed: "",
    website: "https://kacsimpact.org",
    high_need: false,
    addr: "Kennett Square PA",
  },
  {
    id: 74,
    name: "Salvation Army Coatesville Housing Assistance",
    category: "housing",
    urgency: "immediate",
    description: "Emergency shelter referrals and rental assistance.",
    hours: "Mon–Fri 9am–4pm",
    phone: "(610) 384-2954",
    embed: "",
    website: "https://salvationarmy.org",
    high_need: true,
    addr: "250 E Lincoln Hwy, Coatesville PA",
  },
  {
    id: 75,
    name: "St. Agnes Day Room Housing Support",
    category: "housing",
    urgency: "immediate",
    description: "Day shelter with connections to housing resources and case management.",
    hours: "Mon–Fri 9am–2pm",
    phone: "(610) 696-8746",
    embed: "",
    website: "#",
    high_need: true,
    addr: "233 W Gay St, West Chester PA",
  },
  {
    id: 76,
    name: "Chester County Night Shelter",
    category: "housing",
    urgency: "immediate",
    description: "Seasonal overnight shelter for individuals experiencing homelessness.",
    hours: "Evenings",
    phone: "(610) 696-6877",
    embed: "",
    website: "#",
    high_need: true,
    addr: "West Chester PA",
  },
  {
    id: 77,
    name: "Community Action Agency of Delaware County (Chester County Support)",
    category: "housing",
    urgency: "general",
    description: "Rental and utility assistance programs for low-income residents.",
    hours: "Mon–Fri 8:30am–4:30pm",
    phone: "(610) 521-8770",
    embed: "",
    website: "#",
    high_need: false,
    addr: "Chester County, PA",
  },
  {
    id: 78,
    name: "Habitat for Humanity Chester County",
    category: "housing",
    urgency: "general",
    description: "Affordable homeownership opportunities and housing repairs.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 384-7993",
    embed: "",
    website: "https://hfhcc.org",
    high_need: false,
    addr: "1853 E Lincoln Hwy, Coatesville PA",
  },
  {
    id: 79,
    name: "PA 211 Southeast Housing Assistance",
    category: "housing",
    urgency: "immediate",
    description: "24/7 referral service for emergency housing and shelter resources.",
    hours: "24/7",
    phone: "211",
    embed: "",
    website: "https://pa211se.org",
    high_need: true,
    addr: "Chester County, PA",
  },
  {
    id: 80,
    name: "Your Way Home Chester County",
    category: "housing",
    urgency: "immediate",
    description: "Coordinated entry system for people experiencing homelessness.",
    hours: "Mon–Fri 8:30am–4:30pm",
    phone: "(610) 344-6640",
    embed: "",
    website: "https://www.chesco.org",
    high_need: true,
    addr: "Chester County, PA",
  },
  {
    id: 81,
    name: "Brandywine Valley Active Aging Housing Support",
    category: "housing",
    urgency: "general",
    description: "Senior housing referrals and assistance with independent living options.",
    hours: "Mon–Fri 8:30am–4:30pm",
    phone: "(610) 388-7800",
    embed: "",
    website: "https://bvaa.org",
    high_need: false,
    addr: "8800 West Chester Pike, Upper Darby PA",
  },
  {
    id: 82,
    name: "PA Housing Finance Agency (PHFA)",
    category: "housing",
    urgency: "general",
    description: "Statewide rental assistance, foreclosure prevention, and homebuyer programs.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(717) 780-3800",
    embed: "",
    website: "https://www.phfa.org",
    high_need: false,
    addr: "Chester County, PA",
  },
  {
    id: 83,
    name: "Home of the Sparrow",
    category: "housing",
    urgency: "immediate",
    description: "Supportive housing and services for women facing homelessness.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 647-4940",
    embed: "",
    website: "https://homeofthesparrow.org",
    high_need: true,
    addr: "Malvern PA",
  },
  {
    id: 84,
    name: "Human Services Inc. Housing Programs",
    category: "housing",
    urgency: "general",
    description: "Affordable housing and behavioral health residential services.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 380-4660",
    embed: "",
    website: "https://hsinpa.org",
    high_need: false,
    addr: "Coatesville PA",
  },
  {
    id: 85,
    name: "Brandywine Valley Community Services Housing Aid",
    category: "housing",
    urgency: "general",
    description: "Utility and rent assistance for low-income households.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 380-4600",
    embed: "",
    website: "#",
    high_need: false,
    addr: "Coatesville PA",
  },
  {
    id: 86,
    name: "LCH Community Health Housing Referrals",
    category: "housing",
    urgency: "general",
    description: "Connections to housing and social services for underserved populations.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(610) 444-7550",
    embed: "",
    website: "https://lchcommunityhealth.org",
    high_need: false,
    addr: "Kennett Square PA",
  },
  {
    id: 87,
    name: "Maternal & Child Health Consortium Housing Support",
    category: "housing",
    urgency: "general",
    description: "Housing assistance for families with young children.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 344-5370",
    embed: "",
    website: "https://ccmchc.org",
    high_need: false,
    addr: "West Chester PA",
  },
  {
    id: 88,
    name: "PA Department of Human Services Housing Programs",
    category: "housing",
    urgency: "general",
    description: "State assistance for housing, rent, and utilities.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(800) 692-7462",
    embed: "",
    website: "https://www.dhs.pa.gov",
    high_need: false,
    addr: "Chester County, PA",
  },
  {
    id: 89,
    name: "Catholic Housing Services Chester County",
    category: "housing",
    urgency: "general",
    description: "Affordable housing and case management services.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 435-1541",
    embed: "",
    website: "#",
    high_need: false,
    addr: "Chester County, PA",
  },
  {
    id: 90,
    name: "Interfaith Housing Assistance Corporation",
    category: "housing",
    urgency: "general",
    description: "Affordable housing development and rental support.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 436-2540",
    embed: "",
    website: "#",
    high_need: false,
    addr: "West Chester PA",
  },
  {
    id: 91,
    name: "United Way of Chester County Housing Help",
    category: "housing",
    urgency: "general",
    description: "Referrals and financial assistance for housing stability.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 429-9400",
    embed: "",
    website: "https://unitedwaychestercounty.org",
    high_need: false,
    addr: "Exton PA",
  },
  {
    id: 92,
    name: "Housing Equality Center of PA",
    category: "housing",
    urgency: "general",
    description: "Fair housing support and legal assistance for discrimination cases.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(267) 419-8918",
    embed: "",
    website: "https://equalhousing.org",
    high_need: false,
    addr: "Chester County, PA",
  },
  {
    id: 93,
    name: "PA Legal Aid Housing Assistance",
    category: "housing",
    urgency: "immediate",
    description: "Free legal help for eviction, foreclosure, and tenant rights.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(877) 429-5994",
    embed: "",
    website: "https://palegalaid.net",
    high_need: true,
    addr: "Chester County, PA",
  },
  {
    id: 94,
    name: "Community Resource Center Housing Help",
    category: "housing",
    urgency: "general",
    description: "Case management and housing referrals.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 933-1105",
    embed: "",
    website: "#",
    high_need: false,
    addr: "Phoenixville PA",
  },
  {
    id: 95,
    name: "West Chester Area Senior Center Housing Aid",
    category: "housing",
    urgency: "general",
    description: "Housing assistance and referrals for seniors.",
    hours: "Mon–Fri 8am–4pm",
    phone: "(610) 431-4242",
    embed: "",
    website: "#",
    high_need: false,
    addr: "West Chester PA",
  },
  {
    id: 96,
    name: "Downingtown Area Senior Center Housing Support",
    category: "housing",
    urgency: "general",
    description: "Senior housing referrals and assistance.",
    hours: "Mon–Fri 8am–4pm",
    phone: "(610) 269-3939",
    embed: "",
    website: "#",
    high_need: false,
    addr: "Downingtown PA",
  },
  {
    id: 97,
    name: "Chester County Reentry Coalition Housing",
    category: "housing",
    urgency: "general",
    description: "Housing support for individuals reentering from incarceration.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 344-4222",
    embed: "",
    website: "#",
    high_need: false,
    addr: "West Chester PA",
  },
  {
    id: 98,
    name: "Veterans Affairs Housing Assistance (VA)",
    category: "housing",
    urgency: "immediate",
    description: "Housing programs and vouchers for veterans experiencing homelessness.",
    hours: "Mon–Fri 8am–4:30pm",
    phone: "(877) 424-3838",
    embed: "",
    website: "https://www.va.gov",
    high_need: true,
    addr: "Chester County, PA",
  },
  {
    id: 99,
    name: "Pennsylvania 2-1-1 Housing Referrals",
    category: "housing",
    urgency: "immediate",
    description: "24/7 referrals to shelters, rental help, and housing services.",
    hours: "24/7",
    phone: "211",
    embed: "",
    website: "https://pa211.org",
    high_need: true,
    addr: "Chester County, PA",
  },
  {
    id: 100,
    name: "Chester County Continuum of Care",
    category: "housing",
    urgency: "general",
    description: "Coordinated housing and homelessness response network.",
    hours: "Mon–Fri 8:30am–4:30pm",
    phone: "(610) 344-6640",
    embed: "",
    website: "https://www.chesco.org",
    high_need: false,
    addr: "Chester County, PA",
  },
  {
    id: 101,
    name: "PA CareerLink Chester County",
    category: "jobs",
    urgency: "general",
    description: "Job search help, resume support, and training programs.",
    hours: "Mon–Fri 8:30am–4:30pm",
    phone: "(610) 280-1010",
    embed: "",
    website: "https://pacareerlink.pa.gov",
    high_need: false,
    addr: "479 Thomas Jones Way, Exton PA",
  },
  {
    id: 102,
    name: "Chester County OIC",
    category: "jobs",
    urgency: "general",
    description: "Workforce training, GED prep, and job placement services.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 692-6810",
    embed: "",
    website: "https://ccoic.org",
    high_need: false,
    addr: "28 W Market St, West Chester PA",
  },
  {
    id: 103,
    name: "Goodwill Job Training Programs",
    category: "jobs",
    urgency: "general",
    description: "Job training and employment placement support.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 429-1207",
    embed: "",
    website: "https://goodwillde.org",
    high_need: false,
    addr: "Exton PA",
  },
  {
    id: 104,
    name: "Chester County Workforce Development Board",
    category: "jobs",
    urgency: "general",
    description: "Career development programs and employer connections.",
    hours: "Mon–Fri 8:30am–4:30pm",
    phone: "(610) 344-6610",
    embed: "",
    website: "https://www.chesco.org",
    high_need: false,
    addr: "West Chester PA",
  },
  {
    id: 105,
    name: "Technical College High School Adult Education",
    category: "jobs",
    urgency: "general",
    description: "Adult vocational training and certification programs.",
    hours: "Varies",
    phone: "(610) 692-1964",
    embed: "",
    website: "https://www.cciu.org",
    high_need: false,
    addr: "West Grove PA",
  },
  {
    id: 106,
    name: "Delaware County Community College (Chester County Campus)",
    category: "jobs",
    urgency: "general",
    description: "Career training, certifications, and workforce programs.",
    hours: "Mon–Fri 8am–6pm",
    phone: "(610) 359-5000",
    embed: "",
    website: "https://www.dccc.edu",
    high_need: false,
    addr: "901 S Media Line Rd, Media PA",
  },
  {
    id: 107,
    name: "Manpower Staffing West Chester",
    category: "jobs",
    urgency: "immediate",
    description: "Temporary and permanent job placement services.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(610) 696-3355",
    embed: "",
    website: "https://www.manpower.com",
    high_need: true,
    addr: "West Chester PA",
  },
  {
    id: 108,
    name: "Express Employment Professionals",
    category: "jobs",
    urgency: "immediate",
    description: "Staffing agency offering local job placements.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(610) 363-5800",
    embed: "",
    website: "https://www.expresspros.com",
    high_need: true,
    addr: "Exton PA",
  },
  {
    id: 109,
    name: "Robert Half Staffing",
    category: "jobs",
    urgency: "general",
    description: "Professional staffing and job placement services.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(610) 882-1600",
    embed: "",
    website: "https://www.roberthalf.com",
    high_need: false,
    addr: "Wayne PA",
  },
  {
    id: 110,
    name: "PeopleShare Staffing",
    category: "jobs",
    urgency: "immediate",
    description: "Temporary and full-time job placement services.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(610) 321-0330",
    embed: "",
    website: "https://www.peopleshareworks.com",
    high_need: true,
    addr: "Exton PA",
  },
  {
    id: 111,
    name: "Adecco Staffing",
    category: "jobs",
    urgency: "immediate",
    description: "Job placement and workforce solutions.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(610) 647-2200",
    embed: "",
    website: "https://www.adecco.com",
    high_need: true,
    addr: "Malvern PA",
  },
  {
    id: 112,
    name: "Chester County Library Career Resources",
    category: "jobs",
    urgency: "general",
    description: "Resume help, job search tools, and free computer access.",
    hours: "Daily",
    phone: "(610) 280-2600",
    embed: "",
    website: "https://chescolibraries.org",
    high_need: false,
    addr: "Exton PA",
  },
  {
    id: 113,
    name: "United Way Financial Stability Programs",
    category: "jobs",
    urgency: "general",
    description: "Job readiness and financial coaching.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 429-9400",
    embed: "",
    website: "https://unitedwaychestercounty.org",
    high_need: false,
    addr: "Exton PA",
  },
  {
    id: 114,
    name: "Chester County Intermediate Unit Workforce Programs",
    category: "jobs",
    urgency: "general",
    description: "Career readiness and youth employment programs.",
    hours: "Mon–Fri 8am–4pm",
    phone: "(484) 237-5000",
    embed: "",
    website: "https://www.cciu.org",
    high_need: false,
    addr: "Downingtown PA",
  },
  {
    id: 115,
    name: "PA Apprenticeship Programs",
    category: "jobs",
    urgency: "general",
    description: "Paid apprenticeships in trades and technical careers.",
    hours: "Varies",
    phone: "(717) 787-4671",
    embed: "",
    website: "https://www.apprenticeship.pa.gov",
    high_need: false,
    addr: "Chester County, PA",
  },
  {
    id: 116,
    name: "Job Corps Outreach (Chester County)",
    category: "jobs",
    urgency: "general",
    description: "Free education and job training for young adults.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(800) 733-5627",
    embed: "",
    website: "https://www.jobcorps.gov",
    high_need: false,
    addr: "Chester County, PA",
  },
  {
    id: 117,
    name: "Veterans Employment Services",
    category: "jobs",
    urgency: "general",
    description: "Job placement and training for veterans.",
    hours: "Mon–Fri 8am–4pm",
    phone: "(610) 280-1010",
    embed: "",
    website: "#",
    high_need: false,
    addr: "Exton PA",
  },
  {
    id: 118,
    name: "Chester County Chamber of Business & Industry",
    category: "jobs",
    urgency: "general",
    description: "Networking, job boards, and employer connections.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 725-9100",
    embed: "",
    website: "https://www.cccbi.org",
    high_need: false,
    addr: "Exton PA",
  },
  {
    id: 119,
    name: "LinkedIn Local Chester County",
    category: "jobs",
    urgency: "general",
    description: "Professional networking events and job connections.",
    hours: "Events vary",
    phone: "",
    embed: "",
    website: "https://www.linkedin.com",
    high_need: false,
    addr: "Chester County, PA",
  },
  {
    id: 120,
    name: "Indeed Job Search (Chester County)",
    category: "jobs",
    urgency: "general",
    description: "Online job search platform with local listings.",
    hours: "24/7",
    phone: "",
    embed: "",
    website: "https://www.indeed.com",
    high_need: false,
    addr: "Chester County, PA",
  },
  {
    id: 121,
    name: "Career Wardrobe Chester County",
    category: "jobs",
    urgency: "general",
    description: "Professional clothing and job readiness support.",
    hours: "By appointment",
    phone: "(610) 566-1776",
    embed: "",
    website: "https://careerwardrobe.org",
    high_need: false,
    addr: "Chester County, PA",
  },
  {
    id: 122,
    name: "Chester County Economic Development Council",
    category: "jobs",
    urgency: "general",
    description: "Business growth and workforce development programs.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 321-8220",
    embed: "",
    website: "https://ccedcpa.com",
    high_need: false,
    addr: "Exton PA",
  },
  {
    id: 123,
    name: "Workforce Solutions (EARN Program)",
    category: "jobs",
    urgency: "general",
    description: "Employment, advancement, and retention network support.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 280-1010",
    embed: "",
    website: "#",
    high_need: false,
    addr: "Exton PA",
  },
  {
    id: 124,
    name: "JEVS Human Services",
    category: "jobs",
    urgency: "general",
    description: "Career training and job placement services.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(215) 854-1800",
    embed: "",
    website: "https://www.jevshumanservices.org",
    high_need: false,
    addr: "Chester County, PA",
  },
  {
    id: 125,
    name: "Office Team (Admin Staffing)",
    category: "jobs",
    urgency: "immediate",
    description: "Administrative and office job placements.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(610) 882-1600",
    embed: "",
    website: "https://www.roberthalf.com",
    high_need: true,
    addr: "Wayne PA",
  },
  {
    id: 126,
    name: "Chester County SCORE Mentors",
    category: "jobs",
    urgency: "general",
    description: "Free business mentoring and entrepreneurship support.",
    hours: "Varies",
    phone: "(610) 344-6910",
    embed: "",
    website: "https://score.org",
    high_need: false,
    addr: "West Chester PA",
  },
  {
    id: 127,
    name: "Small Business Development Center (SBDC)",
    category: "jobs",
    urgency: "general",
    description: "Business startup and job creation support.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 436-2627",
    embed: "",
    website: "https://pasbdc.org",
    high_need: false,
    addr: "West Chester PA",
  },
  {
    id: 128,
    name: "GigSmart Local Jobs",
    category: "jobs",
    urgency: "immediate",
    description: "App-based gig and flexible job opportunities.",
    hours: "24/7",
    phone: "",
    embed: "",
    website: "https://gigsmart.com",
    high_need: true,
    addr: "Chester County, PA",
  },
  {
    id: 129,
    name: "Snagajob Chester County",
    category: "jobs",
    urgency: "immediate",
    description: "Hourly job listings and quick applications.",
    hours: "24/7",
    phone: "",
    embed: "",
    website: "https://www.snagajob.com",
    high_need: true,
    addr: "Chester County, PA",
  },
  {
    id: 130,
    name: "Chester County Hospital Careers",
    category: "jobs",
    urgency: "general",
    description: "Healthcare job openings and career opportunities.",
    hours: "24/7 online",
    phone: "(610) 431-5000",
    embed: "",
    website: "https://www.pennmedicine.org/careers",
    high_need: false,
    addr: "West Chester PA",
  },
  {
    id: 131,
    name: "Main Line Health Careers",
    category: "jobs",
    urgency: "general",
    description: "Healthcare employment and training programs.",
    hours: "24/7 online",
    phone: "(484) 565-1000",
    embed: "",
    website: "https://www.mainlinehealth.org/careers",
    high_need: false,
    addr: "Paoli PA",
  },
  {
    id: 132,
    name: "Tower Health Careers",
    category: "jobs",
    urgency: "general",
    description: "Hospital and healthcare job opportunities.",
    hours: "24/7 online",
    phone: "(610) 983-1000",
    embed: "",
    website: "https://towerhealth.org/careers",
    high_need: false,
    addr: "Phoenixville PA",
  },
  {
    id: 133,
    name: "Chester County Government Jobs",
    category: "jobs",
    urgency: "general",
    description: "Public sector employment opportunities.",
    hours: "Mon–Fri 8:30am–4:30pm",
    phone: "(610) 344-6000",
    embed: "",
    website: "https://www.chesco.org/jobs",
    high_need: false,
    addr: "West Chester PA",
  },
  {
    id: 134,
    name: "USAJobs (Federal Jobs)",
    category: "jobs",
    urgency: "general",
    description: "Federal employment opportunities in the region.",
    hours: "24/7",
    phone: "",
    embed: "",
    website: "https://www.usajobs.gov",
    high_need: false,
    addr: "Chester County, PA",
  },
  {
    id: 135,
    name: "Chester County School District Jobs",
    category: "jobs",
    urgency: "general",
    description: "Teaching and school staff employment opportunities.",
    hours: "Mon–Fri",
    phone: "",
    embed: "",
    website: "#",
    high_need: false,
    addr: "Chester County, PA",
  },
  {
    id: 136,
    name: "Wawa Careers (Regional HQ)",
    category: "jobs",
    urgency: "immediate",
    description: "Retail and corporate job opportunities.",
    hours: "24/7 online",
    phone: "",
    embed: "",
    website: "https://www.wawa.com/careers",
    high_need: true,
    addr: "Wawa PA",
  },
  {
    id: 137,
    name: "Amazon Jobs (Regional Warehouses)",
    category: "jobs",
    urgency: "immediate",
    description: "Warehouse and logistics job opportunities.",
    hours: "24/7 online",
    phone: "",
    embed: "",
    website: "https://www.amazon.jobs",
    high_need: true,
    addr: "Chester County, PA",
  },
  {
    id: 138,
    name: "UPS Jobs Chester County",
    category: "jobs",
    urgency: "immediate",
    description: "Package handling and delivery jobs.",
    hours: "Varies",
    phone: "",
    embed: "",
    website: "https://www.jobs-ups.com",
    high_need: true,
    addr: "Chester County, PA",
  },
  {
    id: 139,
    name: "Chester County Retail Jobs Network",
    category: "jobs",
    urgency: "immediate",
    description: "Retail employment opportunities across the county.",
    hours: "Varies",
    phone: "",
    embed: "",
    website: "#",
    high_need: true,
    addr: "Chester County, PA",
  },
  {
    id: 140,
    name: "Chester County Hospitality Jobs",
    category: "jobs",
    urgency: "immediate",
    description: "Restaurant and hospitality job openings.",
    hours: "Varies",
    phone: "",
    embed: "",
    website: "#",
    high_need: true,
    addr: "Chester County, PA",
  },
  {
    id: 141,
    name: "Chester County Library System",
    category: "education",
    urgency: "general",
    description: "Free access to books, tutoring, ESL classes, and digital resources.",
    hours: "Varies by branch",
    phone: "(610) 280-2600",
    embed: "",
    website: "https://chescolibraries.org",
    high_need: false,
    addr: "450 Exton Square Pkwy, Exton PA",
  },
  {
    id: 142,
    name: "Chester County Intermediate Unit (CCIU)",
    category: "education",
    urgency: "general",
    description: "Educational services, special education, and workforce training programs.",
    hours: "Mon–Fri 8am–4pm",
    phone: "(484) 237-5000",
    embed: "",
    website: "https://www.cciu.org",
    high_need: false,
    addr: "455 Boot Rd, Downingtown PA",
  },
  {
    id: 143,
    name: "Delaware County Community College (Exton Center)",
    category: "education",
    urgency: "general",
    description: "Associate degrees, certifications, and continuing education programs.",
    hours: "Mon–Fri 8am–6pm",
    phone: "(610) 280-5120",
    embed: "",
    website: "https://www.dccc.edu",
    high_need: false,
    addr: "906 Springdale Dr, Exton PA",
  },
  {
    id: 144,
    name: "West Chester University",
    category: "education",
    urgency: "general",
    description: "Undergraduate, graduate, and continuing education programs.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(610) 436-1000",
    embed: "",
    website: "https://www.wcupa.edu",
    high_need: false,
    addr: "700 S High St, West Chester PA",
  },
  {
    id: 145,
    name: "Technical College High School",
    category: "education",
    urgency: "general",
    description: "Career and technical education programs for high school students and adults.",
    hours: "Mon–Fri 7:30am–3pm",
    phone: "(610) 692-1964",
    embed: "",
    website: "https://www.cciu.org/tchs",
    high_need: false,
    addr: "Pickering Campus, Phoenixville PA",
  },
  {
    id: 146,
    name: "Chester County OIC Education Programs",
    category: "education",
    urgency: "general",
    description: "GED prep, adult literacy, and workforce education.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 692-6810",
    embed: "",
    website: "https://ccoic.org",
    high_need: false,
    addr: "28 W Market St, West Chester PA",
  },
  {
    id: 147,
    name: "PA CareerLink Training Programs",
    category: "education",
    urgency: "general",
    description: "Career training, certifications, and skill-building programs.",
    hours: "Mon–Fri 8:30am–4:30pm",
    phone: "(610) 280-1010",
    embed: "",
    website: "https://pacareerlink.pa.gov",
    high_need: false,
    addr: "Exton PA",
  },
  {
    id: 148,
    name: "Literacy Council of Chester County",
    category: "education",
    urgency: "general",
    description: "Adult literacy, ESL, and GED preparation classes.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 692-1966",
    embed: "",
    website: "https://lccc-pa.org",
    high_need: false,
    addr: "West Chester PA",
  },
  {
    id: 149,
    name: "Chester County Night School",
    category: "education",
    urgency: "general",
    description: "Adult evening classes including GED and enrichment courses.",
    hours: "Evenings",
    phone: "(610) 692-1964",
    embed: "",
    website: "#",
    high_need: false,
    addr: "Downingtown PA",
  },
  {
    id: 150,
    name: "Brandywine Valley SPCA Humane Education",
    category: "education",
    urgency: "general",
    description: "Educational programs focused on animal welfare and community engagement.",
    hours: "Varies",
    phone: "(610) 692-6113",
    embed: "",
    website: "https://bvspca.org",
    high_need: false,
    addr: "West Chester PA",
  },
  {
    id: 151,
    name: "YMCA of Greater Brandywine Education Programs",
    category: "education",
    urgency: "general",
    description: "After-school programs, tutoring, and youth development.",
    hours: "Varies",
    phone: "(610) 363-9622",
    embed: "",
    website: "https://ymcagbw.org",
    high_need: false,
    addr: "Exton PA",
  },
  {
    id: 152,
    name: "Chester County Historical Society Education",
    category: "education",
    urgency: "general",
    description: "History education programs, exhibits, and research resources.",
    hours: "Tue–Sat 10am–4pm",
    phone: "(610) 692-4800",
    embed: "",
    website: "https://mycchc.org",
    high_need: false,
    addr: "225 N High St, West Chester PA",
  },
  {
    id: 153,
    name: "Art Association of Chester County",
    category: "education",
    urgency: "general",
    description: "Art classes, workshops, and community education programs.",
    hours: "Mon–Sat",
    phone: "(610) 696-5600",
    embed: "",
    website: "https://chestercountyarts.org",
    high_need: false,
    addr: "100 N Bradford Ave, West Chester PA",
  },
  {
    id: 154,
    name: "Chester County School District Adult Education",
    category: "education",
    urgency: "general",
    description: "Continuing education and adult learning programs.",
    hours: "Varies",
    phone: "",
    embed: "",
    website: "#",
    high_need: false,
    addr: "Chester County, PA",
  },
  {
    id: 155,
    name: "Penn State Extension Chester County",
    category: "education",
    urgency: "general",
    description: "Workshops and educational programs in agriculture, health, and youth development.",
    hours: "Mon–Fri 8:30am–4:30pm",
    phone: "(610) 696-3500",
    embed: "",
    website: "https://extension.psu.edu",
    high_need: false,
    addr: "601 Westtown Rd, West Chester PA",
  },
  {
    id: 156,
    name: "Stroud Water Research Center Education",
    category: "education",
    urgency: "general",
    description: "Environmental education and science programs.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 268-2153",
    embed: "",
    website: "https://www.stroudcenter.org",
    high_need: false,
    addr: "970 Spencer Rd, Avondale PA",
  },
  {
    id: 157,
    name: "Chester County Parks & Recreation Programs",
    category: "education",
    urgency: "general",
    description: "Outdoor education and recreational learning opportunities.",
    hours: "Varies",
    phone: "(610) 344-6415",
    embed: "",
    website: "https://www.chesco.org",
    high_need: false,
    addr: "Chester County, PA",
  },
  {
    id: 158,
    name: "The Garage Community & Youth Center",
    category: "education",
    urgency: "general",
    description: "After-school programs, mentoring, and youth education.",
    hours: "Mon–Fri afternoons",
    phone: "(610) 692-5550",
    embed: "",
    website: "https://thegarageyouthcenter.org",
    high_need: false,
    addr: "West Chester PA",
  },
  {
    id: 159,
    name: "Chester County Futures",
    category: "education",
    urgency: "general",
    description: "College readiness and academic support for students.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 524-0005",
    embed: "",
    website: "https://ccfutures.org",
    high_need: false,
    addr: "Exton PA",
  },
  {
    id: 160,
    name: "La Comunidad Hispana Education Programs",
    category: "education",
    urgency: "general",
    description: "Bilingual education, ESL, and youth programs.",
    hours: "Mon–Fri 8am–5pm",
    phone: "(610) 444-7550",
    embed: "",
    website: "https://lchcommunityhealth.org",
    high_need: false,
    addr: "Kennett Square PA",
  },
  {
    id: 161,
    name: "Downingtown Area Adult Night School",
    category: "education",
    urgency: "general",
    description: "Adult education classes including GED prep and enrichment courses.",
    hours: "Evenings",
    phone: "(610) 269-8460",
    embed: "",
    website: "#",
    high_need: false,
    addr: "Downingtown PA",
  },
  {
    id: 162,
    name: "Owen J. Roberts Adult Education Program",
    category: "education",
    urgency: "general",
    description: "Continuing education and skills training for adults.",
    hours: "Evenings",
    phone: "(610) 469-5100",
    embed: "",
    website: "#",
    high_need: false,
    addr: "Pottstown PA",
  },
  {
    id: 163,
    name: "Chester County Family Academy",
    category: "education",
    urgency: "general",
    description: "Parent education and early childhood learning programs.",
    hours: "Varies",
    phone: "(610) 344-5370",
    embed: "",
    website: "#",
    high_need: false,
    addr: "West Chester PA",
  },
  {
    id: 164,
    name: "Kennett Library Learning Programs",
    category: "education",
    urgency: "general",
    description: "Workshops, tutoring, and community education events.",
    hours: "Varies",
    phone: "(610) 444-2702",
    embed: "",
    website: "https://kennettlibrary.org",
    high_need: false,
    addr: "320 E State St, Kennett Square PA",
  },
  {
    id: 165,
    name: "Phoenixville Public Library Programs",
    category: "education",
    urgency: "general",
    description: "Educational workshops, literacy programs, and tutoring.",
    hours: "Varies",
    phone: "(610) 933-3013",
    embed: "",
    website: "https://phoenixvillelibrary.org",
    high_need: false,
    addr: "183 2nd Ave, Phoenixville PA",
  },
  {
    id: 166,
    name: "Oxford Public Library Learning Center",
    category: "education",
    urgency: "general",
    description: "Free tutoring, ESL, and digital literacy classes.",
    hours: "Varies",
    phone: "(610) 932-9625",
    embed: "",
    website: "#",
    high_need: false,
    addr: "48 S 2nd St, Oxford PA",
  },
  {
    id: 167,
    name: "Chester County Digital Literacy Initiative",
    category: "education",
    urgency: "general",
    description: "Computer skills training and internet access programs.",
    hours: "Varies",
    phone: "(610) 280-2600",
    embed: "",
    website: "#",
    high_need: false,
    addr: "Chester County, PA",
  },
  {
    id: 168,
    name: "Coatesville Area Public Library Programs",
    category: "education",
    urgency: "general",
    description: "After-school tutoring, reading programs, and workshops.",
    hours: "Varies",
    phone: "(610) 384-4115",
    embed: "",
    website: "#",
    high_need: false,
    addr: "501 E Lincoln Hwy, Coatesville PA",
  },
  {
    id: 169,
    name: "West Chester Area School District Adult Ed",
    category: "education",
    urgency: "general",
    description: "Continuing education and skill-building courses.",
    hours: "Evenings",
    phone: "(484) 266-1000",
    embed: "",
    website: "#",
    high_need: false,
    addr: "West Chester PA",
  },
  {
    id: 170,
    name: "Tredyffrin Public Library Programs",
    category: "education",
    urgency: "general",
    description: "STEM programs, tutoring, and educational workshops.",
    hours: "Varies",
    phone: "(610) 688-7092",
    embed: "",
    website: "https://tredyffrinlibraries.org",
    high_need: false,
    addr: "582 Upper Gulph Rd, Strafford PA",
  },
  {
    id: 171,
    name: "Chester County STEM Academy",
    category: "education",
    urgency: "general",
    description: "STEM-focused enrichment and youth education programs.",
    hours: "Varies",
    phone: "",
    embed: "",
    website: "#",
    high_need: false,
    addr: "Chester County, PA",
  },
  {
    id: 172,
    name: "Avon Grove School District Adult Education",
    category: "education",
    urgency: "general",
    description: "Adult learning and continuing education programs.",
    hours: "Evenings",
    phone: "(610) 869-2441",
    embed: "",
    website: "#",
    high_need: false,
    addr: "West Grove PA",
  },
  {
    id: 173,
    name: "Chester County Environmental Education Center",
    category: "education",
    urgency: "general",
    description: "Nature-based learning and environmental programs.",
    hours: "Varies",
    phone: "(610) 344-6415",
    embed: "",
    website: "#",
    high_need: false,
    addr: "Chester County, PA",
  },
  {
    id: 174,
    name: "Immaculata University Continuing Education",
    category: "education",
    urgency: "general",
    description: "Adult degree completion and certificate programs.",
    hours: "Mon–Fri 9am–5pm",
    phone: "(610) 647-4400",
    embed: "",
    website: "https://www.immaculata.edu",
    high_need: false,
    addr: "1145 King Rd, Immaculata PA",
  },
  {
    id: 175,
    name: "Cheyney University Outreach Programs",
    category: "education",
    urgency: "general",
    description: "Community education and workforce readiness programs.",
    hours: "Varies",
    phone: "(610) 399-2000",
    embed: "",
    website: "https://www.cheyney.edu",
    high_need: false,
    addr: "Cheyney PA",
  },
  {
    id: 176,
    name: "Chester County Youth Leadership Program",
    category: "education",
    urgency: "general",
    description: "Leadership development and civic engagement for youth.",
    hours: "Varies",
    phone: "(610) 344-6600",
    embed: "",
    website: "#",
    high_need: false,
    addr: "Chester County, PA",
  },
  {
    id: 177,
    name: "Downingtown Library Educational Programs",
    category: "education",
    urgency: "general",
    description: "Literacy programs, tutoring, and workshops.",
    hours: "Varies",
    phone: "(610) 269-2741",
    embed: "",
    website: "https://downingtownlibrary.org",
    high_need: false,
    addr: "122 Wallace Ave, Downingtown PA",
  },
  {
    id: 178,
    name: "Malvern Public Library Programs",
    category: "education",
    urgency: "general",
    description: "Educational events, tutoring, and youth programs.",
    hours: "Varies",
    phone: "(610) 644-7259",
    embed: "",
    website: "#",
    high_need: false,
    addr: "1 E 1st Ave, Malvern PA",
  },
  {
    id: 179,
    name: "Chester County Coding & Tech Workshops",
    category: "education",
    urgency: "general",
    description: "Intro to coding, tech skills, and digital careers.",
    hours: "Varies",
    phone: "",
    embed: "",
    website: "#",
    high_need: false,
    addr: "Chester County, PA",
  },
  {
    id: 180,
    name: "Brandywine Wallace Elementary Family Programs",
    category: "education",
    urgency: "general",
    description: "Family literacy and community education programs.",
    hours: "Varies",
    phone: "(610) 383-3765",
    embed: "",
    website: "#",
    high_need: false,
    addr: "Coatesville PA",
  },
];

export const EMERGENCY = [
  {
    emoji: "🏚️",
    title: "Night Shelter",
    description: "Chester County Night Shelter — walk-in 5pm nightly",
    phone: "(610) 696-6877",
    cat: "Housing",
  },
  {
    emoji: "🍽️",
    title: "Hot Meals Daily",
    description: "Phoenixville Good Samaritan — hot lunch 11:30am every day",
    phone: "(610) 933-0741",
    cat: "Food",
  },
  {
    emoji: "📞",
    title: "Crisis Line 24/7",
    description: "Crisis Text Line — text HOME to 741741",
    phone: "741741 (text)",
    cat: "Mental Health",
  },
  {
    emoji: "🚨",
    title: "DV Crisis Shelter",
    description: "YWCA confidential emergency shelter — available now",
    phone: "(610) 692-7273",
    cat: "Safety",
  },
];
